service:
  name: user-service
  grpcPort: 9102

log:
  level: debug

postgres:
  dsn: postgres://bbs_user_app:local_user_pass@127.0.0.1:5432/bbs?sslmode=disable&search_path=bbs_user
  debug: false

kafka:
  brokers:
    - 127.0.0.1:9092
  topic: user.events

snowflake:
  workerId: 2

jwt:
  secret: bbs-local-dev-secret
  ttl: 168h

password:
  minLength: 8

