// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/proto/content.proto

package contentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug              string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Type              string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title             string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body              string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Tags              []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId          int64                  `protobuf:"varint,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status            int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt       int64                  `protobuf:"varint,11,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CategoryId        int64                  `protobuf:"varint,12,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ViewCount         int64                  `protobuf:"varint,13,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	BountyScore       int64                  `protobuf:"varint,14,opt,name=bounty_score,json=bountyScore,proto3" json:"bounty_score,omitempty"`
	QaStatus          string                 `protobuf:"bytes,15,opt,name=qa_status,json=qaStatus,proto3" json:"qa_status,omitempty"`
	AcceptedCommentId int64                  `protobuf:"varint,16,opt,name=accepted_comment_id,json=acceptedCommentId,proto3" json:"accepted_comment_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TopicInfo) Reset() {
	*x = TopicInfo{}
	mi := &file_api_proto_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicInfo) ProtoMessage() {}

func (x *TopicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicInfo.ProtoReflect.Descriptor instead.
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{0}
}

func (x *TopicInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopicInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TopicInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TopicInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopicInfo) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *TopicInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TopicInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *TopicInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TopicInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TopicInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *TopicInfo) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *TopicInfo) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *TopicInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *TopicInfo) GetBountyScore() int64 {
	if x != nil {
		return x.BountyScore
	}
	return 0
}

func (x *TopicInfo) GetQaStatus() string {
	if x != nil {
		return x.QaStatus
	}
	return ""
}

func (x *TopicInfo) GetAcceptedCommentId() int64 {
	if x != nil {
		return x.AcceptedCommentId
	}
	return 0
}

type ArticleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId      int64                  `protobuf:"varint,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,12,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ViewCount     int64                  `protobuf:"varint,13,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleInfo) Reset() {
	*x = ArticleInfo{}
	mi := &file_api_proto_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleInfo) ProtoMessage() {}

func (x *ArticleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleInfo.ProtoReflect.Descriptor instead.
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ArticleInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ArticleInfo) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ArticleInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *ArticleInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ArticleInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ArticleInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ArticleInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ArticleInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ArticleInfo) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *ArticleInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type TopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Topic         *TopicInfo             `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicResponse) Reset() {
	*x = TopicResponse{}
	mi := &file_api_proto_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicResponse) ProtoMessage() {}

func (x *TopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicResponse.ProtoReflect.Descriptor instead.
func (*TopicResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{2}
}

func (x *TopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TopicResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TopicResponse) GetTopic() *TopicInfo {
	if x != nil {
		return x.Topic
	}
	return nil
}

type TopicListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TopicInfo           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicListResponse) Reset() {
	*x = TopicListResponse{}
	mi := &file_api_proto_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicListResponse) ProtoMessage() {}

func (x *TopicListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicListResponse.ProtoReflect.Descriptor instead.
func (*TopicListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{3}
}

func (x *TopicListResponse) GetItems() []*TopicInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type ArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Article       *ArticleInfo           `protobuf:"bytes,3,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleResponse) Reset() {
	*x = ArticleResponse{}
	mi := &file_api_proto_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResponse) ProtoMessage() {}

func (x *ArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResponse.ProtoReflect.Descriptor instead.
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArticleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ArticleResponse) GetArticle() *ArticleInfo {
	if x != nil {
		return x.Article
	}
	return nil
}

type ArticleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ArticleInfo         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListResponse) Reset() {
	*x = ArticleListResponse{}
	mi := &file_api_proto_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListResponse) ProtoMessage() {}

func (x *ArticleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListResponse.ProtoReflect.Descriptor instead.
func (*ArticleListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{5}
}

func (x *ArticleListResponse) GetItems() []*ArticleInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type TagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	mi := &file_api_proto_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{6}
}

func (x *TagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TagInfo             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListResponse) Reset() {
	*x = TagListResponse{}
	mi := &file_api_proto_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponse) ProtoMessage() {}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponse.ProtoReflect.Descriptor instead.
func (*TagListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{7}
}

func (x *TagListResponse) GetItems() []*TagInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type CategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	TopicCount    int64                  `protobuf:"varint,7,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	mi := &file_api_proto_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{8}
}

func (x *CategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfo) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryInfo) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CategoryInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CategoryInfo) GetTopicCount() int64 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

func (x *CategoryInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CategoryInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Category      *CategoryInfo          `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_api_proto_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{9}
}

func (x *CategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CategoryResponse) GetCategory() *CategoryInfo {
	if x != nil {
		return x.Category
	}
	return nil
}

type CategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CategoryInfo        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_api_proto_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryListResponse) GetItems() []*CategoryInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId      int64                  `protobuf:"varint,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BountyScore   int64                  `protobuf:"varint,8,opt,name=bounty_score,json=bountyScore,proto3" json:"bounty_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_api_proto_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTopicRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTopicRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTopicRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTopicRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateTopicRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTopicRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *CreateTopicRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateTopicRequest) GetBountyScore() int64 {
	if x != nil {
		return x.BountyScore
	}
	return 0
}

type UpdateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BountyScore   int64                  `protobuf:"varint,6,opt,name=bounty_score,json=bountyScore,proto3" json:"bounty_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicRequest) Reset() {
	*x = UpdateTopicRequest{}
	mi := &file_api_proto_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicRequest) ProtoMessage() {}

func (x *UpdateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicRequest.ProtoReflect.Descriptor instead.
func (*UpdateTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTopicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTopicRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTopicRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UpdateTopicRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateTopicRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateTopicRequest) GetBountyScore() int64 {
	if x != nil {
		return x.BountyScore
	}
	return 0
}

type TopicIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicIDRequest) Reset() {
	*x = TopicIDRequest{}
	mi := &file_api_proto_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicIDRequest) ProtoMessage() {}

func (x *TopicIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicIDRequest.ProtoReflect.Descriptor instead.
func (*TopicIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{13}
}

func (x *TopicIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AcceptTopicCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	CommentId     int64                  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptTopicCommentRequest) Reset() {
	*x = AcceptTopicCommentRequest{}
	mi := &file_api_proto_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptTopicCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptTopicCommentRequest) ProtoMessage() {}

func (x *AcceptTopicCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptTopicCommentRequest.ProtoReflect.Descriptor instead.
func (*AcceptTopicCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{14}
}

func (x *AcceptTopicCommentRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *AcceptTopicCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *AcceptTopicCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTopicRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Key:
	//
	//	*GetTopicRequest_Id
	//	*GetTopicRequest_Slug
	Key           isGetTopicRequest_Key `protobuf_oneof:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicRequest) Reset() {
	*x = GetTopicRequest{}
	mi := &file_api_proto_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicRequest) ProtoMessage() {}

func (x *GetTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{15}
}

func (x *GetTopicRequest) GetKey() isGetTopicRequest_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetTopicRequest) GetId() int64 {
	if x != nil {
		if x, ok := x.Key.(*GetTopicRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetTopicRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Key.(*GetTopicRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetTopicRequest_Key interface {
	isGetTopicRequest_Key()
}

type GetTopicRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetTopicRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetTopicRequest_Id) isGetTopicRequest_Key() {}

func (*GetTopicRequest_Slug) isGetTopicRequest_Key() {}

type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	CategoryId    int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Sort          string                 `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_api_proto_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{16}
}

func (x *ListTopicsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListTopicsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListTopicsRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListTopicsRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ListTopicsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTopicsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTopicsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListTopicsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId      int64                  `protobuf:"varint,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_api_proto_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{17}
}

func (x *CreateArticleRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateArticleRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateArticleRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *CreateArticleRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateArticleRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_api_proto_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateArticleRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UpdateArticleRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *UpdateArticleRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ArticleIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleIDRequest) Reset() {
	*x = ArticleIDRequest{}
	mi := &file_api_proto_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleIDRequest) ProtoMessage() {}

func (x *ArticleIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleIDRequest.ProtoReflect.Descriptor instead.
func (*ArticleIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{19}
}

func (x *ArticleIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Key:
	//
	//	*GetArticleRequest_Id
	//	*GetArticleRequest_Slug
	Key           isGetArticleRequest_Key `protobuf_oneof:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_api_proto_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{20}
}

func (x *GetArticleRequest) GetKey() isGetArticleRequest_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetArticleRequest) GetId() int64 {
	if x != nil {
		if x, ok := x.Key.(*GetArticleRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetArticleRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Key.(*GetArticleRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isGetArticleRequest_Key interface {
	isGetArticleRequest_Key()
}

type GetArticleRequest_Id struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetArticleRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"`
}

func (*GetArticleRequest_Id) isGetArticleRequest_Key() {}

func (*GetArticleRequest_Slug) isGetArticleRequest_Key() {}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	AuthorId      int64                  `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Sort          string                 `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_api_proto_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{21}
}

func (x *ListArticlesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListArticlesRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListArticlesRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *ListArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListArticlesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type FeedArticlesByTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedArticlesByTimeRequest) Reset() {
	*x = FeedArticlesByTimeRequest{}
	mi := &file_api_proto_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedArticlesByTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedArticlesByTimeRequest) ProtoMessage() {}

func (x *FeedArticlesByTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedArticlesByTimeRequest.ProtoReflect.Descriptor instead.
func (*FeedArticlesByTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{22}
}

func (x *FeedArticlesByTimeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FeedArticlesByTimeRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_api_proto_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{23}
}

func (x *ListCategoriesRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCategoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CategoryIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryIDRequest) Reset() {
	*x = CategoryIDRequest{}
	mi := &file_api_proto_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryIDRequest) ProtoMessage() {}

func (x *CategoryIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryIDRequest.ProtoReflect.Descriptor instead.
func (*CategoryIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{24}
}

func (x *CategoryIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpsertCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCategoryRequest) Reset() {
	*x = UpsertCategoryRequest{}
	mi := &file_api_proto_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCategoryRequest) ProtoMessage() {}

func (x *UpsertCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpsertCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{25}
}

func (x *UpsertCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertCategoryRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpsertCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpsertCategoryRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpsertCategoryRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_api_proto_content_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{26}
}

func (x *ListTagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTagsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListTagsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AutocompleteTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutocompleteTagsRequest) Reset() {
	*x = AutocompleteTagsRequest{}
	mi := &file_api_proto_content_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutocompleteTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteTagsRequest) ProtoMessage() {}

func (x *AutocompleteTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_content_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteTagsRequest.ProtoReflect.Descriptor instead.
func (*AutocompleteTagsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_content_proto_rawDescGZIP(), []int{27}
}

func (x *AutocompleteTagsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AutocompleteTagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_api_proto_content_proto protoreflect.FileDescriptor

const file_api_proto_content_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/content.proto\x12\x0ebbs.content.v1\"\xc7\x03\n" +
	"\tTopicInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1b\n" +
	"\tauthor_id\x18\a \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12!\n" +
	"\fpublished_at\x18\v \x01(\x03R\vpublishedAt\x12\x1f\n" +
	"\vcategory_id\x18\f \x01(\x03R\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"view_count\x18\r \x01(\x03R\tviewCount\x12!\n" +
	"\fbounty_score\x18\x0e \x01(\x03R\vbountyScore\x12\x1b\n" +
	"\tqa_status\x18\x0f \x01(\tR\bqaStatus\x12.\n" +
	"\x13accepted_comment_id\x18\x10 \x01(\x03R\x11acceptedCommentId\"\xdb\x02\n" +
	"\vArticleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\x03R\bauthorId\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12!\n" +
	"\fpublished_at\x18\f \x01(\x03R\vpublishedAt\x12\x1d\n" +
	"\n" +
	"view_count\x18\r \x01(\x03R\tviewCount\"t\n" +
	"\rTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x05topic\x18\x03 \x01(\v2\x19.bbs.content.v1.TopicInfoR\x05topic\"D\n" +
	"\x11TopicListResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.bbs.content.v1.TopicInfoR\x05items\"|\n" +
	"\x0fArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\aarticle\x18\x03 \x01(\v2\x1b.bbs.content.v1.ArticleInfoR\aarticle\"H\n" +
	"\x13ArticleListResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.bbs.content.v1.ArticleInfoR\x05items\"3\n" +
	"\aTagInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"@\n" +
	"\x0fTagListResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.bbs.content.v1.TagInfoR\x05items\"\xf3\x01\n" +
	"\fCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vtopic_count\x18\a \x01(\x03R\n" +
	"topicCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\x80\x01\n" +
	"\x10CategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\bcategory\x18\x03 \x01(\v2\x1c.bbs.content.v1.CategoryInfoR\bcategory\"J\n" +
	"\x14CategoryListResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.bbs.content.v1.CategoryInfoR\x05items\"\xdb\x01\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12!\n" +
	"\fbounty_score\x18\b \x01(\x03R\vbountyScore\"\xa6\x01\n" +
	"\x12UpdateTopicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12!\n" +
	"\fbounty_score\x18\x06 \x01(\x03R\vbountyScore\" \n" +
	"\x0eTopicIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"n\n" +
	"\x19AcceptTopicCommentRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"@\n" +
	"\x0fGetTopicRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\x05\n" +
	"\x03key\"\xd1\x01\n" +
	"\x11ListTopicsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04sort\x18\b \x01(\tR\x04sort\"\xbc\x01\n" +
	"\x14CreateArticleRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1b\n" +
	"\tauthor_id\x18\a \x01(\x03R\bauthorId\"\x9b\x01\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"\"\n" +
	"\x10ArticleIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\x11GetArticleRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\x05\n" +
	"\x03key\"\x9e\x01\n" +
	"\x13ListArticlesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\tR\x04sort\"I\n" +
	"\x19FeedArticlesByTimeRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"]\n" +
	"\x15ListCategoriesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"#\n" +
	"\x11CategoryIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9d\x01\n" +
	"\x15UpsertCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"U\n" +
	"\x0fListTagsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"E\n" +
	"\x17AutocompleteTagsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit2\xc8\x0f\n" +
	"\x0eContentService\x12P\n" +
	"\vCreateTopic\x12\".bbs.content.v1.CreateTopicRequest\x1a\x1d.bbs.content.v1.TopicResponse\x12P\n" +
	"\vUpdateTopic\x12\".bbs.content.v1.UpdateTopicRequest\x1a\x1d.bbs.content.v1.TopicResponse\x12M\n" +
	"\fPublishTopic\x12\x1e.bbs.content.v1.TopicIDRequest\x1a\x1d.bbs.content.v1.TopicResponse\x12J\n" +
	"\tHideTopic\x12\x1e.bbs.content.v1.TopicIDRequest\x1a\x1d.bbs.content.v1.TopicResponse\x12M\n" +
	"\fArchiveTopic\x12\x1e.bbs.content.v1.TopicIDRequest\x1a\x1d.bbs.content.v1.TopicResponse\x12^\n" +
	"\x12AcceptTopicComment\x12).bbs.content.v1.AcceptTopicCommentRequest\x1a\x1d.bbs.content.v1.TopicResponse\x12J\n" +
	"\bGetTopic\x12\x1f.bbs.content.v1.GetTopicRequest\x1a\x1d.bbs.content.v1.TopicResponse\x12R\n" +
	"\n" +
	"ListTopics\x12!.bbs.content.v1.ListTopicsRequest\x1a!.bbs.content.v1.TopicListResponse\x12V\n" +
	"\rCreateArticle\x12$.bbs.content.v1.CreateArticleRequest\x1a\x1f.bbs.content.v1.ArticleResponse\x12V\n" +
	"\rUpdateArticle\x12$.bbs.content.v1.UpdateArticleRequest\x1a\x1f.bbs.content.v1.ArticleResponse\x12S\n" +
	"\x0ePublishArticle\x12 .bbs.content.v1.ArticleIDRequest\x1a\x1f.bbs.content.v1.ArticleResponse\x12P\n" +
	"\vHideArticle\x12 .bbs.content.v1.ArticleIDRequest\x1a\x1f.bbs.content.v1.ArticleResponse\x12S\n" +
	"\x0eArchiveArticle\x12 .bbs.content.v1.ArticleIDRequest\x1a\x1f.bbs.content.v1.ArticleResponse\x12P\n" +
	"\n" +
	"GetArticle\x12!.bbs.content.v1.GetArticleRequest\x1a\x1f.bbs.content.v1.ArticleResponse\x12X\n" +
	"\fListArticles\x12#.bbs.content.v1.ListArticlesRequest\x1a#.bbs.content.v1.ArticleListResponse\x12d\n" +
	"\x12FeedArticlesByTime\x12).bbs.content.v1.FeedArticlesByTimeRequest\x1a#.bbs.content.v1.ArticleListResponse\x12]\n" +
	"\x0eListCategories\x12%.bbs.content.v1.ListCategoriesRequest\x1a$.bbs.content.v1.CategoryListResponse\x12R\n" +
	"\vGetCategory\x12!.bbs.content.v1.CategoryIDRequest\x1a .bbs.content.v1.CategoryResponse\x12Y\n" +
	"\x0eCreateCategory\x12%.bbs.content.v1.UpsertCategoryRequest\x1a .bbs.content.v1.CategoryResponse\x12Y\n" +
	"\x0eUpdateCategory\x12%.bbs.content.v1.UpsertCategoryRequest\x1a .bbs.content.v1.CategoryResponse\x12U\n" +
	"\x0eDeleteCategory\x12!.bbs.content.v1.CategoryIDRequest\x1a .bbs.content.v1.CategoryResponse\x12L\n" +
	"\bListTags\x12\x1f.bbs.content.v1.ListTagsRequest\x1a\x1f.bbs.content.v1.TagListResponse\x12\\\n" +
	"\x10AutocompleteTags\x12'.bbs.content.v1.AutocompleteTagsRequest\x1a\x1f.bbs.content.v1.TagListResponseB/Z-content-service/api/proto/contentpb;contentpbb\x06proto3"

var (
	file_api_proto_content_proto_rawDescOnce sync.Once
	file_api_proto_content_proto_rawDescData []byte
)

func file_api_proto_content_proto_rawDescGZIP() []byte {
	file_api_proto_content_proto_rawDescOnce.Do(func() {
		file_api_proto_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_content_proto_rawDesc), len(file_api_proto_content_proto_rawDesc)))
	})
	return file_api_proto_content_proto_rawDescData
}

var file_api_proto_content_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_proto_content_proto_goTypes = []any{
	(*TopicInfo)(nil),                 // 0: bbs.content.v1.TopicInfo
	(*ArticleInfo)(nil),               // 1: bbs.content.v1.ArticleInfo
	(*TopicResponse)(nil),             // 2: bbs.content.v1.TopicResponse
	(*TopicListResponse)(nil),         // 3: bbs.content.v1.TopicListResponse
	(*ArticleResponse)(nil),           // 4: bbs.content.v1.ArticleResponse
	(*ArticleListResponse)(nil),       // 5: bbs.content.v1.ArticleListResponse
	(*TagInfo)(nil),                   // 6: bbs.content.v1.TagInfo
	(*TagListResponse)(nil),           // 7: bbs.content.v1.TagListResponse
	(*CategoryInfo)(nil),              // 8: bbs.content.v1.CategoryInfo
	(*CategoryResponse)(nil),          // 9: bbs.content.v1.CategoryResponse
	(*CategoryListResponse)(nil),      // 10: bbs.content.v1.CategoryListResponse
	(*CreateTopicRequest)(nil),        // 11: bbs.content.v1.CreateTopicRequest
	(*UpdateTopicRequest)(nil),        // 12: bbs.content.v1.UpdateTopicRequest
	(*TopicIDRequest)(nil),            // 13: bbs.content.v1.TopicIDRequest
	(*AcceptTopicCommentRequest)(nil), // 14: bbs.content.v1.AcceptTopicCommentRequest
	(*GetTopicRequest)(nil),           // 15: bbs.content.v1.GetTopicRequest
	(*ListTopicsRequest)(nil),         // 16: bbs.content.v1.ListTopicsRequest
	(*CreateArticleRequest)(nil),      // 17: bbs.content.v1.CreateArticleRequest
	(*UpdateArticleRequest)(nil),      // 18: bbs.content.v1.UpdateArticleRequest
	(*ArticleIDRequest)(nil),          // 19: bbs.content.v1.ArticleIDRequest
	(*GetArticleRequest)(nil),         // 20: bbs.content.v1.GetArticleRequest
	(*ListArticlesRequest)(nil),       // 21: bbs.content.v1.ListArticlesRequest
	(*FeedArticlesByTimeRequest)(nil), // 22: bbs.content.v1.FeedArticlesByTimeRequest
	(*ListCategoriesRequest)(nil),     // 23: bbs.content.v1.ListCategoriesRequest
	(*CategoryIDRequest)(nil),         // 24: bbs.content.v1.CategoryIDRequest
	(*UpsertCategoryRequest)(nil),     // 25: bbs.content.v1.UpsertCategoryRequest
	(*ListTagsRequest)(nil),           // 26: bbs.content.v1.ListTagsRequest
	(*AutocompleteTagsRequest)(nil),   // 27: bbs.content.v1.AutocompleteTagsRequest
}
var file_api_proto_content_proto_depIdxs = []int32{
	0,  // 0: bbs.content.v1.TopicResponse.topic:type_name -> bbs.content.v1.TopicInfo
	0,  // 1: bbs.content.v1.TopicListResponse.items:type_name -> bbs.content.v1.TopicInfo
	1,  // 2: bbs.content.v1.ArticleResponse.article:type_name -> bbs.content.v1.ArticleInfo
	1,  // 3: bbs.content.v1.ArticleListResponse.items:type_name -> bbs.content.v1.ArticleInfo
	6,  // 4: bbs.content.v1.TagListResponse.items:type_name -> bbs.content.v1.TagInfo
	8,  // 5: bbs.content.v1.CategoryResponse.category:type_name -> bbs.content.v1.CategoryInfo
	8,  // 6: bbs.content.v1.CategoryListResponse.items:type_name -> bbs.content.v1.CategoryInfo
	11, // 7: bbs.content.v1.ContentService.CreateTopic:input_type -> bbs.content.v1.CreateTopicRequest
	12, // 8: bbs.content.v1.ContentService.UpdateTopic:input_type -> bbs.content.v1.UpdateTopicRequest
	13, // 9: bbs.content.v1.ContentService.PublishTopic:input_type -> bbs.content.v1.TopicIDRequest
	13, // 10: bbs.content.v1.ContentService.HideTopic:input_type -> bbs.content.v1.TopicIDRequest
	13, // 11: bbs.content.v1.ContentService.ArchiveTopic:input_type -> bbs.content.v1.TopicIDRequest
	14, // 12: bbs.content.v1.ContentService.AcceptTopicComment:input_type -> bbs.content.v1.AcceptTopicCommentRequest
	15, // 13: bbs.content.v1.ContentService.GetTopic:input_type -> bbs.content.v1.GetTopicRequest
	16, // 14: bbs.content.v1.ContentService.ListTopics:input_type -> bbs.content.v1.ListTopicsRequest
	17, // 15: bbs.content.v1.ContentService.CreateArticle:input_type -> bbs.content.v1.CreateArticleRequest
	18, // 16: bbs.content.v1.ContentService.UpdateArticle:input_type -> bbs.content.v1.UpdateArticleRequest
	19, // 17: bbs.content.v1.ContentService.PublishArticle:input_type -> bbs.content.v1.ArticleIDRequest
	19, // 18: bbs.content.v1.ContentService.HideArticle:input_type -> bbs.content.v1.ArticleIDRequest
	19, // 19: bbs.content.v1.ContentService.ArchiveArticle:input_type -> bbs.content.v1.ArticleIDRequest
	20, // 20: bbs.content.v1.ContentService.GetArticle:input_type -> bbs.content.v1.GetArticleRequest
	21, // 21: bbs.content.v1.ContentService.ListArticles:input_type -> bbs.content.v1.ListArticlesRequest
	22, // 22: bbs.content.v1.ContentService.FeedArticlesByTime:input_type -> bbs.content.v1.FeedArticlesByTimeRequest
	23, // 23: bbs.content.v1.ContentService.ListCategories:input_type -> bbs.content.v1.ListCategoriesRequest
	24, // 24: bbs.content.v1.ContentService.GetCategory:input_type -> bbs.content.v1.CategoryIDRequest
	25, // 25: bbs.content.v1.ContentService.CreateCategory:input_type -> bbs.content.v1.UpsertCategoryRequest
	25, // 26: bbs.content.v1.ContentService.UpdateCategory:input_type -> bbs.content.v1.UpsertCategoryRequest
	24, // 27: bbs.content.v1.ContentService.DeleteCategory:input_type -> bbs.content.v1.CategoryIDRequest
	26, // 28: bbs.content.v1.ContentService.ListTags:input_type -> bbs.content.v1.ListTagsRequest
	27, // 29: bbs.content.v1.ContentService.AutocompleteTags:input_type -> bbs.content.v1.AutocompleteTagsRequest
	2,  // 30: bbs.content.v1.ContentService.CreateTopic:output_type -> bbs.content.v1.TopicResponse
	2,  // 31: bbs.content.v1.ContentService.UpdateTopic:output_type -> bbs.content.v1.TopicResponse
	2,  // 32: bbs.content.v1.ContentService.PublishTopic:output_type -> bbs.content.v1.TopicResponse
	2,  // 33: bbs.content.v1.ContentService.HideTopic:output_type -> bbs.content.v1.TopicResponse
	2,  // 34: bbs.content.v1.ContentService.ArchiveTopic:output_type -> bbs.content.v1.TopicResponse
	2,  // 35: bbs.content.v1.ContentService.AcceptTopicComment:output_type -> bbs.content.v1.TopicResponse
	2,  // 36: bbs.content.v1.ContentService.GetTopic:output_type -> bbs.content.v1.TopicResponse
	3,  // 37: bbs.content.v1.ContentService.ListTopics:output_type -> bbs.content.v1.TopicListResponse
	4,  // 38: bbs.content.v1.ContentService.CreateArticle:output_type -> bbs.content.v1.ArticleResponse
	4,  // 39: bbs.content.v1.ContentService.UpdateArticle:output_type -> bbs.content.v1.ArticleResponse
	4,  // 40: bbs.content.v1.ContentService.PublishArticle:output_type -> bbs.content.v1.ArticleResponse
	4,  // 41: bbs.content.v1.ContentService.HideArticle:output_type -> bbs.content.v1.ArticleResponse
	4,  // 42: bbs.content.v1.ContentService.ArchiveArticle:output_type -> bbs.content.v1.ArticleResponse
	4,  // 43: bbs.content.v1.ContentService.GetArticle:output_type -> bbs.content.v1.ArticleResponse
	5,  // 44: bbs.content.v1.ContentService.ListArticles:output_type -> bbs.content.v1.ArticleListResponse
	5,  // 45: bbs.content.v1.ContentService.FeedArticlesByTime:output_type -> bbs.content.v1.ArticleListResponse
	10, // 46: bbs.content.v1.ContentService.ListCategories:output_type -> bbs.content.v1.CategoryListResponse
	9,  // 47: bbs.content.v1.ContentService.GetCategory:output_type -> bbs.content.v1.CategoryResponse
	9,  // 48: bbs.content.v1.ContentService.CreateCategory:output_type -> bbs.content.v1.CategoryResponse
	9,  // 49: bbs.content.v1.ContentService.UpdateCategory:output_type -> bbs.content.v1.CategoryResponse
	9,  // 50: bbs.content.v1.ContentService.DeleteCategory:output_type -> bbs.content.v1.CategoryResponse
	7,  // 51: bbs.content.v1.ContentService.ListTags:output_type -> bbs.content.v1.TagListResponse
	7,  // 52: bbs.content.v1.ContentService.AutocompleteTags:output_type -> bbs.content.v1.TagListResponse
	30, // [30:53] is the sub-list for method output_type
	7,  // [7:30] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_content_proto_init() }
func file_api_proto_content_proto_init() {
	if File_api_proto_content_proto != nil {
		return
	}
	file_api_proto_content_proto_msgTypes[15].OneofWrappers = []any{
		(*GetTopicRequest_Id)(nil),
		(*GetTopicRequest_Slug)(nil),
	}
	file_api_proto_content_proto_msgTypes[20].OneofWrappers = []any{
		(*GetArticleRequest_Id)(nil),
		(*GetArticleRequest_Slug)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_content_proto_rawDesc), len(file_api_proto_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_content_proto_goTypes,
		DependencyIndexes: file_api_proto_content_proto_depIdxs,
		MessageInfos:      file_api_proto_content_proto_msgTypes,
	}.Build()
	File_api_proto_content_proto = out.File
	file_api_proto_content_proto_goTypes = nil
	file_api_proto_content_proto_depIdxs = nil
}
