// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.1
// source: chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_CreateRoom_FullMethodName                = "/bbs.chat.v1.ChatService/CreateRoom"
	ChatService_LookupRoom_FullMethodName                = "/bbs.chat.v1.ChatService/LookupRoom"
	ChatService_JoinRoom_FullMethodName                  = "/bbs.chat.v1.ChatService/JoinRoom"
	ChatService_LeaveRoom_FullMethodName                 = "/bbs.chat.v1.ChatService/LeaveRoom"
	ChatService_ListSidebar_FullMethodName               = "/bbs.chat.v1.ChatService/ListSidebar"
	ChatService_ListMessages_FullMethodName              = "/bbs.chat.v1.ChatService/ListMessages"
	ChatService_SendMessage_FullMethodName               = "/bbs.chat.v1.ChatService/SendMessage"
	ChatService_DeleteMessage_FullMethodName             = "/bbs.chat.v1.ChatService/DeleteMessage"
	ChatService_AdvanceRead_FullMethodName               = "/bbs.chat.v1.ChatService/AdvanceRead"
	ChatService_CreateGroup_FullMethodName               = "/bbs.chat.v1.ChatService/CreateGroup"
	ChatService_UpdateGroup_FullMethodName               = "/bbs.chat.v1.ChatService/UpdateGroup"
	ChatService_DeleteGroup_FullMethodName               = "/bbs.chat.v1.ChatService/DeleteGroup"
	ChatService_MoveGroup_FullMethodName                 = "/bbs.chat.v1.ChatService/MoveGroup"
	ChatService_PlaceRoom_FullMethodName                 = "/bbs.chat.v1.ChatService/PlaceRoom"
	ChatService_UpdateAnnouncement_FullMethodName        = "/bbs.chat.v1.ChatService/UpdateAnnouncement"
	ChatService_MarkAnnouncementSeen_FullMethodName      = "/bbs.chat.v1.ChatService/MarkAnnouncementSeen"
	ChatService_ValidateRoomSubscriptions_FullMethodName = "/bbs.chat.v1.ChatService/ValidateRoomSubscriptions"
	ChatService_ListRoomMembers_FullMethodName           = "/bbs.chat.v1.ChatService/ListRoomMembers"
	ChatService_UpdateRoomMemberRole_FullMethodName      = "/bbs.chat.v1.ChatService/UpdateRoomMemberRole"
	ChatService_MuteRoomMember_FullMethodName            = "/bbs.chat.v1.ChatService/MuteRoomMember"
	ChatService_UnmuteRoomMember_FullMethodName          = "/bbs.chat.v1.ChatService/UnmuteRoomMember"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*RoomDetailsResponse, error)
	LookupRoom(ctx context.Context, in *LookupRoomRequest, opts ...grpc.CallOption) (*RoomDetailsResponse, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*RoomDetailsResponse, error)
	LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	ListSidebar(ctx context.Context, in *ListSidebarRequest, opts ...grpc.CallOption) (*SidebarResponse, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*MessagePageResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
	AdvanceRead(ctx context.Context, in *AdvanceReadRequest, opts ...grpc.CallOption) (*AdvanceReadResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	MoveGroup(ctx context.Context, in *MoveGroupRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	PlaceRoom(ctx context.Context, in *PlaceRoomRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	UpdateAnnouncement(ctx context.Context, in *UpdateAnnouncementRequest, opts ...grpc.CallOption) (*RoomResponse, error)
	MarkAnnouncementSeen(ctx context.Context, in *MarkAnnouncementSeenRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	ValidateRoomSubscriptions(ctx context.Context, in *ValidateRoomSubscriptionsRequest, opts ...grpc.CallOption) (*ValidateRoomSubscriptionsResponse, error)
	ListRoomMembers(ctx context.Context, in *ListRoomMembersRequest, opts ...grpc.CallOption) (*RoomMemberListResponse, error)
	UpdateRoomMemberRole(ctx context.Context, in *UpdateRoomMemberRoleRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	MuteRoomMember(ctx context.Context, in *MuteRoomMemberRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	UnmuteRoomMember(ctx context.Context, in *UnmuteRoomMemberRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*RoomDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomDetailsResponse)
	err := c.cc.Invoke(ctx, ChatService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) LookupRoom(ctx context.Context, in *LookupRoomRequest, opts ...grpc.CallOption) (*RoomDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomDetailsResponse)
	err := c.cc.Invoke(ctx, ChatService_LookupRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*RoomDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomDetailsResponse)
	err := c.cc.Invoke(ctx, ChatService_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, ChatService_LeaveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListSidebar(ctx context.Context, in *ListSidebarRequest, opts ...grpc.CallOption) (*SidebarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SidebarResponse)
	err := c.cc.Invoke(ctx, ChatService_ListSidebar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*MessagePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagePageResponse)
	err := c.cc.Invoke(ctx, ChatService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, ChatService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageResponse)
	err := c.cc.Invoke(ctx, ChatService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AdvanceRead(ctx context.Context, in *AdvanceReadRequest, opts ...grpc.CallOption) (*AdvanceReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvanceReadResponse)
	err := c.cc.Invoke(ctx, ChatService_AdvanceRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, ChatService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, ChatService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, ChatService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) MoveGroup(ctx context.Context, in *MoveGroupRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, ChatService_MoveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) PlaceRoom(ctx context.Context, in *PlaceRoomRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, ChatService_PlaceRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpdateAnnouncement(ctx context.Context, in *UpdateAnnouncementRequest, opts ...grpc.CallOption) (*RoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomResponse)
	err := c.cc.Invoke(ctx, ChatService_UpdateAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) MarkAnnouncementSeen(ctx context.Context, in *MarkAnnouncementSeenRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, ChatService_MarkAnnouncementSeen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ValidateRoomSubscriptions(ctx context.Context, in *ValidateRoomSubscriptionsRequest, opts ...grpc.CallOption) (*ValidateRoomSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRoomSubscriptionsResponse)
	err := c.cc.Invoke(ctx, ChatService_ValidateRoomSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListRoomMembers(ctx context.Context, in *ListRoomMembersRequest, opts ...grpc.CallOption) (*RoomMemberListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomMemberListResponse)
	err := c.cc.Invoke(ctx, ChatService_ListRoomMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpdateRoomMemberRole(ctx context.Context, in *UpdateRoomMemberRoleRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, ChatService_UpdateRoomMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) MuteRoomMember(ctx context.Context, in *MuteRoomMemberRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, ChatService_MuteRoomMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UnmuteRoomMember(ctx context.Context, in *UnmuteRoomMemberRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, ChatService_UnmuteRoomMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
type ChatServiceServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*RoomDetailsResponse, error)
	LookupRoom(context.Context, *LookupRoomRequest) (*RoomDetailsResponse, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*RoomDetailsResponse, error)
	LeaveRoom(context.Context, *LeaveRoomRequest) (*MembershipResponse, error)
	ListSidebar(context.Context, *ListSidebarRequest) (*SidebarResponse, error)
	ListMessages(context.Context, *ListMessagesRequest) (*MessagePageResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error)
	AdvanceRead(context.Context, *AdvanceReadRequest) (*AdvanceReadResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*GroupResponse, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*GroupResponse, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*SimpleResponse, error)
	MoveGroup(context.Context, *MoveGroupRequest) (*SimpleResponse, error)
	PlaceRoom(context.Context, *PlaceRoomRequest) (*MembershipResponse, error)
	UpdateAnnouncement(context.Context, *UpdateAnnouncementRequest) (*RoomResponse, error)
	MarkAnnouncementSeen(context.Context, *MarkAnnouncementSeenRequest) (*MembershipResponse, error)
	ValidateRoomSubscriptions(context.Context, *ValidateRoomSubscriptionsRequest) (*ValidateRoomSubscriptionsResponse, error)
	ListRoomMembers(context.Context, *ListRoomMembersRequest) (*RoomMemberListResponse, error)
	UpdateRoomMemberRole(context.Context, *UpdateRoomMemberRoleRequest) (*MembershipResponse, error)
	MuteRoomMember(context.Context, *MuteRoomMemberRequest) (*MembershipResponse, error)
	UnmuteRoomMember(context.Context, *UnmuteRoomMemberRequest) (*MembershipResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*RoomDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedChatServiceServer) LookupRoom(context.Context, *LookupRoomRequest) (*RoomDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupRoom not implemented")
}
func (UnimplementedChatServiceServer) JoinRoom(context.Context, *JoinRoomRequest) (*RoomDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedChatServiceServer) LeaveRoom(context.Context, *LeaveRoomRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveRoom not implemented")
}
func (UnimplementedChatServiceServer) ListSidebar(context.Context, *ListSidebarRequest) (*SidebarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSidebar not implemented")
}
func (UnimplementedChatServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*MessagePageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedChatServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServiceServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedChatServiceServer) AdvanceRead(context.Context, *AdvanceReadRequest) (*AdvanceReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvanceRead not implemented")
}
func (UnimplementedChatServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*GroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedChatServiceServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*GroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedChatServiceServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedChatServiceServer) MoveGroup(context.Context, *MoveGroupRequest) (*SimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveGroup not implemented")
}
func (UnimplementedChatServiceServer) PlaceRoom(context.Context, *PlaceRoomRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceRoom not implemented")
}
func (UnimplementedChatServiceServer) UpdateAnnouncement(context.Context, *UpdateAnnouncementRequest) (*RoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAnnouncement not implemented")
}
func (UnimplementedChatServiceServer) MarkAnnouncementSeen(context.Context, *MarkAnnouncementSeenRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAnnouncementSeen not implemented")
}
func (UnimplementedChatServiceServer) ValidateRoomSubscriptions(context.Context, *ValidateRoomSubscriptionsRequest) (*ValidateRoomSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRoomSubscriptions not implemented")
}
func (UnimplementedChatServiceServer) ListRoomMembers(context.Context, *ListRoomMembersRequest) (*RoomMemberListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoomMembers not implemented")
}
func (UnimplementedChatServiceServer) UpdateRoomMemberRole(context.Context, *UpdateRoomMemberRoleRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoomMemberRole not implemented")
}
func (UnimplementedChatServiceServer) MuteRoomMember(context.Context, *MuteRoomMemberRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MuteRoomMember not implemented")
}
func (UnimplementedChatServiceServer) UnmuteRoomMember(context.Context, *UnmuteRoomMemberRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnmuteRoomMember not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_LookupRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).LookupRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_LookupRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).LookupRoom(ctx, req.(*LookupRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_LeaveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).LeaveRoom(ctx, req.(*LeaveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListSidebar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSidebarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListSidebar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListSidebar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListSidebar(ctx, req.(*ListSidebarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AdvanceRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvanceReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AdvanceRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_AdvanceRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AdvanceRead(ctx, req.(*AdvanceReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_MoveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).MoveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_MoveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).MoveGroup(ctx, req.(*MoveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_PlaceRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).PlaceRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_PlaceRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).PlaceRoom(ctx, req.(*PlaceRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdateAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpdateAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpdateAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpdateAnnouncement(ctx, req.(*UpdateAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_MarkAnnouncementSeen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAnnouncementSeenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).MarkAnnouncementSeen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_MarkAnnouncementSeen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).MarkAnnouncementSeen(ctx, req.(*MarkAnnouncementSeenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ValidateRoomSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRoomSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ValidateRoomSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ValidateRoomSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ValidateRoomSubscriptions(ctx, req.(*ValidateRoomSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListRoomMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListRoomMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListRoomMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListRoomMembers(ctx, req.(*ListRoomMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdateRoomMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpdateRoomMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpdateRoomMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpdateRoomMemberRole(ctx, req.(*UpdateRoomMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_MuteRoomMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteRoomMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).MuteRoomMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_MuteRoomMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).MuteRoomMember(ctx, req.(*MuteRoomMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UnmuteRoomMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmuteRoomMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UnmuteRoomMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UnmuteRoomMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UnmuteRoomMember(ctx, req.(*UnmuteRoomMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bbs.chat.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _ChatService_CreateRoom_Handler,
		},
		{
			MethodName: "LookupRoom",
			Handler:    _ChatService_LookupRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _ChatService_JoinRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _ChatService_LeaveRoom_Handler,
		},
		{
			MethodName: "ListSidebar",
			Handler:    _ChatService_ListSidebar_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _ChatService_ListMessages_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _ChatService_DeleteMessage_Handler,
		},
		{
			MethodName: "AdvanceRead",
			Handler:    _ChatService_AdvanceRead_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _ChatService_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _ChatService_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _ChatService_DeleteGroup_Handler,
		},
		{
			MethodName: "MoveGroup",
			Handler:    _ChatService_MoveGroup_Handler,
		},
		{
			MethodName: "PlaceRoom",
			Handler:    _ChatService_PlaceRoom_Handler,
		},
		{
			MethodName: "UpdateAnnouncement",
			Handler:    _ChatService_UpdateAnnouncement_Handler,
		},
		{
			MethodName: "MarkAnnouncementSeen",
			Handler:    _ChatService_MarkAnnouncementSeen_Handler,
		},
		{
			MethodName: "ValidateRoomSubscriptions",
			Handler:    _ChatService_ValidateRoomSubscriptions_Handler,
		},
		{
			MethodName: "ListRoomMembers",
			Handler:    _ChatService_ListRoomMembers_Handler,
		},
		{
			MethodName: "UpdateRoomMemberRole",
			Handler:    _ChatService_UpdateRoomMemberRole_Handler,
		},
		{
			MethodName: "MuteRoomMember",
			Handler:    _ChatService_MuteRoomMember_Handler,
		},
		{
			MethodName: "UnmuteRoomMember",
			Handler:    _ChatService_UnmuteRoomMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
