// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: file_erasure.proto

package filepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EraseUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeletionJobId int64                  `protobuf:"varint,2,opt,name=deletion_job_id,json=deletionJobId,proto3" json:"deletion_job_id,omitempty"`
	PolicyVersion int32                  `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EraseUserDataRequest) Reset() {
	*x = EraseUserDataRequest{}
	mi := &file_file_erasure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseUserDataRequest) ProtoMessage() {}

func (x *EraseUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_erasure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseUserDataRequest.ProtoReflect.Descriptor instead.
func (*EraseUserDataRequest) Descriptor() ([]byte, []int) {
	return file_file_erasure_proto_rawDescGZIP(), []int{0}
}

func (x *EraseUserDataRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EraseUserDataRequest) GetDeletionJobId() int64 {
	if x != nil {
		return x.DeletionJobId
	}
	return 0
}

func (x *EraseUserDataRequest) GetPolicyVersion() int32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type EraseUserDataResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Completed           bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	ArchivedAttachments int64                  `protobuf:"varint,2,opt,name=archived_attachments,json=archivedAttachments,proto3" json:"archived_attachments,omitempty"`
	DeletedDownloads    int64                  `protobuf:"varint,3,opt,name=deleted_downloads,json=deletedDownloads,proto3" json:"deleted_downloads,omitempty"`
	DeletedObjects      int64                  `protobuf:"varint,4,opt,name=deleted_objects,json=deletedObjects,proto3" json:"deleted_objects,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EraseUserDataResponse) Reset() {
	*x = EraseUserDataResponse{}
	mi := &file_file_erasure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseUserDataResponse) ProtoMessage() {}

func (x *EraseUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_erasure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseUserDataResponse.ProtoReflect.Descriptor instead.
func (*EraseUserDataResponse) Descriptor() ([]byte, []int) {
	return file_file_erasure_proto_rawDescGZIP(), []int{1}
}

func (x *EraseUserDataResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *EraseUserDataResponse) GetArchivedAttachments() int64 {
	if x != nil {
		return x.ArchivedAttachments
	}
	return 0
}

func (x *EraseUserDataResponse) GetDeletedDownloads() int64 {
	if x != nil {
		return x.DeletedDownloads
	}
	return 0
}

func (x *EraseUserDataResponse) GetDeletedObjects() int64 {
	if x != nil {
		return x.DeletedObjects
	}
	return 0
}

var File_file_erasure_proto protoreflect.FileDescriptor

const file_file_erasure_proto_rawDesc = "" +
	"\n" +
	"\x12file_erasure.proto\x12\vbbs.file.v1\"~\n" +
	"\x14EraseUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0fdeletion_job_id\x18\x02 \x01(\x03R\rdeletionJobId\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x05R\rpolicyVersion\"\xbe\x01\n" +
	"\x15EraseUserDataResponse\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x121\n" +
	"\x14archived_attachments\x18\x02 \x01(\x03R\x13archivedAttachments\x12+\n" +
	"\x11deleted_downloads\x18\x03 \x01(\x03R\x10deletedDownloads\x12'\n" +
	"\x0fdeleted_objects\x18\x04 \x01(\x03R\x0edeletedObjects2e\n" +
	"\vFileService\x12V\n" +
	"\rEraseUserData\x12!.bbs.file.v1.EraseUserDataRequest\x1a\".bbs.file.v1.EraseUserDataResponseB&Z$user-service/api/proto/filepb;filepbb\x06proto3"

var (
	file_file_erasure_proto_rawDescOnce sync.Once
	file_file_erasure_proto_rawDescData []byte
)

func file_file_erasure_proto_rawDescGZIP() []byte {
	file_file_erasure_proto_rawDescOnce.Do(func() {
		file_file_erasure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_erasure_proto_rawDesc), len(file_file_erasure_proto_rawDesc)))
	})
	return file_file_erasure_proto_rawDescData
}

var file_file_erasure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_erasure_proto_goTypes = []any{
	(*EraseUserDataRequest)(nil),  // 0: bbs.file.v1.EraseUserDataRequest
	(*EraseUserDataResponse)(nil), // 1: bbs.file.v1.EraseUserDataResponse
}
var file_file_erasure_proto_depIdxs = []int32{
	0, // 0: bbs.file.v1.FileService.EraseUserData:input_type -> bbs.file.v1.EraseUserDataRequest
	1, // 1: bbs.file.v1.FileService.EraseUserData:output_type -> bbs.file.v1.EraseUserDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_erasure_proto_init() }
func file_file_erasure_proto_init() {
	if File_file_erasure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_erasure_proto_rawDesc), len(file_file_erasure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_erasure_proto_goTypes,
		DependencyIndexes: file_file_erasure_proto_depIdxs,
		MessageInfos:      file_file_erasure_proto_msgTypes,
	}.Build()
	File_file_erasure_proto = out.File
	file_file_erasure_proto_goTypes = nil
	file_file_erasure_proto_depIdxs = nil
}
