// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migration

import (
	"context"
	"reaction-service/internal/support/config"
)

// Injectors from wire.go:

func InitializeMigrator(ctx context.Context, configPath string) (*Migrator, error) {
	configConfig, err := config.New(configPath)
	if err != nil {
		return nil, err
	}
	db, err := provideDB(configConfig)
	if err != nil {
		return nil, err
	}
	migrator := NewMigrator(db)
	return migrator, nil
}
