// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: credit_erasure.proto

package creditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EraseUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeletionJobId int64                  `protobuf:"varint,2,opt,name=deletion_job_id,json=deletionJobId,proto3" json:"deletion_job_id,omitempty"`
	PolicyVersion int32                  `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EraseUserDataRequest) Reset() {
	*x = EraseUserDataRequest{}
	mi := &file_credit_erasure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseUserDataRequest) ProtoMessage() {}

func (x *EraseUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_erasure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseUserDataRequest.ProtoReflect.Descriptor instead.
func (*EraseUserDataRequest) Descriptor() ([]byte, []int) {
	return file_credit_erasure_proto_rawDescGZIP(), []int{0}
}

func (x *EraseUserDataRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EraseUserDataRequest) GetDeletionJobId() int64 {
	if x != nil {
		return x.DeletionJobId
	}
	return 0
}

func (x *EraseUserDataRequest) GetPolicyVersion() int32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type EraseUserDataResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Completed               bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	AnonymizedLedgerEntries int64                  `protobuf:"varint,2,opt,name=anonymized_ledger_entries,json=anonymizedLedgerEntries,proto3" json:"anonymized_ledger_entries,omitempty"`
	AnonymizedReservations  int64                  `protobuf:"varint,3,opt,name=anonymized_reservations,json=anonymizedReservations,proto3" json:"anonymized_reservations,omitempty"`
	DeletedCheckIns         int64                  `protobuf:"varint,4,opt,name=deleted_check_ins,json=deletedCheckIns,proto3" json:"deleted_check_ins,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EraseUserDataResponse) Reset() {
	*x = EraseUserDataResponse{}
	mi := &file_credit_erasure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseUserDataResponse) ProtoMessage() {}

func (x *EraseUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_erasure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseUserDataResponse.ProtoReflect.Descriptor instead.
func (*EraseUserDataResponse) Descriptor() ([]byte, []int) {
	return file_credit_erasure_proto_rawDescGZIP(), []int{1}
}

func (x *EraseUserDataResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *EraseUserDataResponse) GetAnonymizedLedgerEntries() int64 {
	if x != nil {
		return x.AnonymizedLedgerEntries
	}
	return 0
}

func (x *EraseUserDataResponse) GetAnonymizedReservations() int64 {
	if x != nil {
		return x.AnonymizedReservations
	}
	return 0
}

func (x *EraseUserDataResponse) GetDeletedCheckIns() int64 {
	if x != nil {
		return x.DeletedCheckIns
	}
	return 0
}

var File_credit_erasure_proto protoreflect.FileDescriptor

const file_credit_erasure_proto_rawDesc = "" +
	"\n" +
	"\x14credit_erasure.proto\x12\rbbs.credit.v1\"~\n" +
	"\x14EraseUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0fdeletion_job_id\x18\x02 \x01(\x03R\rdeletionJobId\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x05R\rpolicyVersion\"\xd6\x01\n" +
	"\x15EraseUserDataResponse\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x12:\n" +
	"\x19anonymized_ledger_entries\x18\x02 \x01(\x03R\x17anonymizedLedgerEntries\x127\n" +
	"\x17anonymized_reservations\x18\x03 \x01(\x03R\x16anonymizedReservations\x12*\n" +
	"\x11deleted_check_ins\x18\x04 \x01(\x03R\x0fdeletedCheckIns2k\n" +
	"\rCreditService\x12Z\n" +
	"\rEraseUserData\x12#.bbs.credit.v1.EraseUserDataRequest\x1a$.bbs.credit.v1.EraseUserDataResponseB*Z(user-service/api/proto/creditpb;creditpbb\x06proto3"

var (
	file_credit_erasure_proto_rawDescOnce sync.Once
	file_credit_erasure_proto_rawDescData []byte
)

func file_credit_erasure_proto_rawDescGZIP() []byte {
	file_credit_erasure_proto_rawDescOnce.Do(func() {
		file_credit_erasure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credit_erasure_proto_rawDesc), len(file_credit_erasure_proto_rawDesc)))
	})
	return file_credit_erasure_proto_rawDescData
}

var file_credit_erasure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_credit_erasure_proto_goTypes = []any{
	(*EraseUserDataRequest)(nil),  // 0: bbs.credit.v1.EraseUserDataRequest
	(*EraseUserDataResponse)(nil), // 1: bbs.credit.v1.EraseUserDataResponse
}
var file_credit_erasure_proto_depIdxs = []int32{
	0, // 0: bbs.credit.v1.CreditService.EraseUserData:input_type -> bbs.credit.v1.EraseUserDataRequest
	1, // 1: bbs.credit.v1.CreditService.EraseUserData:output_type -> bbs.credit.v1.EraseUserDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_credit_erasure_proto_init() }
func file_credit_erasure_proto_init() {
	if File_credit_erasure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credit_erasure_proto_rawDesc), len(file_credit_erasure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credit_erasure_proto_goTypes,
		DependencyIndexes: file_credit_erasure_proto_depIdxs,
		MessageInfos:      file_credit_erasure_proto_msgTypes,
	}.Build()
	File_credit_erasure_proto = out.File
	file_credit_erasure_proto_goTypes = nil
	file_credit_erasure_proto_depIdxs = nil
}
