// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: notification_erasure.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EraseUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeletionJobId int64                  `protobuf:"varint,2,opt,name=deletion_job_id,json=deletionJobId,proto3" json:"deletion_job_id,omitempty"`
	PolicyVersion int32                  `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EraseUserDataRequest) Reset() {
	*x = EraseUserDataRequest{}
	mi := &file_notification_erasure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EraseUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EraseUserDataRequest) ProtoMessage() {}

func (x *EraseUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_erasure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EraseUserDataRequest.ProtoReflect.Descriptor instead.
func (*EraseUserDataRequest) Descriptor() ([]byte, []int) {
	return file_notification_erasure_proto_rawDescGZIP(), []int{0}
}

func (x *EraseUserDataRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EraseUserDataRequest) GetDeletionJobId() int64 {
	if x != nil {
		return x.DeletionJobId
	}
	return 0
}

func (x *EraseUserDataRequest) GetPolicyVersion() int32 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

type MutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationResponse) Reset() {
	*x = MutationResponse{}
	mi := &file_notification_erasure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResponse) ProtoMessage() {}

func (x *MutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_erasure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResponse.ProtoReflect.Descriptor instead.
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return file_notification_erasure_proto_rawDescGZIP(), []int{1}
}

func (x *MutationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MutationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_notification_erasure_proto protoreflect.FileDescriptor

const file_notification_erasure_proto_rawDesc = "" +
	"\n" +
	"\x1anotification_erasure.proto\x12\x13bbs.notification.v1\"~\n" +
	"\x14EraseUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0fdeletion_job_id\x18\x02 \x01(\x03R\rdeletionJobId\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x05R\rpolicyVersion\"F\n" +
	"\x10MutationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x80\x01\n" +
	"\x1bInternalNotificationService\x12a\n" +
	"\rEraseUserData\x12).bbs.notification.v1.EraseUserDataRequest\x1a%.bbs.notification.v1.MutationResponseB6Z4user-service/api/proto/notificationpb;notificationpbb\x06proto3"

var (
	file_notification_erasure_proto_rawDescOnce sync.Once
	file_notification_erasure_proto_rawDescData []byte
)

func file_notification_erasure_proto_rawDescGZIP() []byte {
	file_notification_erasure_proto_rawDescOnce.Do(func() {
		file_notification_erasure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_erasure_proto_rawDesc), len(file_notification_erasure_proto_rawDesc)))
	})
	return file_notification_erasure_proto_rawDescData
}

var file_notification_erasure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_erasure_proto_goTypes = []any{
	(*EraseUserDataRequest)(nil), // 0: bbs.notification.v1.EraseUserDataRequest
	(*MutationResponse)(nil),     // 1: bbs.notification.v1.MutationResponse
}
var file_notification_erasure_proto_depIdxs = []int32{
	0, // 0: bbs.notification.v1.InternalNotificationService.EraseUserData:input_type -> bbs.notification.v1.EraseUserDataRequest
	1, // 1: bbs.notification.v1.InternalNotificationService.EraseUserData:output_type -> bbs.notification.v1.MutationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_erasure_proto_init() }
func file_notification_erasure_proto_init() {
	if File_notification_erasure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_erasure_proto_rawDesc), len(file_notification_erasure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_erasure_proto_goTypes,
		DependencyIndexes: file_notification_erasure_proto_depIdxs,
		MessageInfos:      file_notification_erasure_proto_msgTypes,
	}.Build()
	File_notification_erasure_proto = out.File
	file_notification_erasure_proto_goTypes = nil
	file_notification_erasure_proto_depIdxs = nil
}
