// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: credit.proto

package creditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_credit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{0}
}

func (x *Balance) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Balance) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Balance) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId string                 `protobuf:"bytes,7,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,8,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      int64                  `protobuf:"varint,9,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_credit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerEntry) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LedgerEntry) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *LedgerEntry) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *LedgerEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LedgerEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LedgerEntry) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *LedgerEntry) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *LedgerEntry) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *LedgerEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DailyCheckIn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LatestDay       string                 `protobuf:"bytes,3,opt,name=latest_day,json=latestDay,proto3" json:"latest_day,omitempty"`
	ConsecutiveDays int32                  `protobuf:"varint,4,opt,name=consecutive_days,json=consecutiveDays,proto3" json:"consecutive_days,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyCheckIn) Reset() {
	*x = DailyCheckIn{}
	mi := &file_credit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyCheckIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyCheckIn) ProtoMessage() {}

func (x *DailyCheckIn) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyCheckIn.ProtoReflect.Descriptor instead.
func (*DailyCheckIn) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{2}
}

func (x *DailyCheckIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DailyCheckIn) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DailyCheckIn) GetLatestDay() string {
	if x != nil {
		return x.LatestDay
	}
	return ""
}

func (x *DailyCheckIn) GetConsecutiveDays() int32 {
	if x != nil {
		return x.ConsecutiveDays
	}
	return 0
}

func (x *DailyCheckIn) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DailyCheckIn) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_credit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_credit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type ListLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerRequest) Reset() {
	*x = ListLedgerRequest{}
	mi := &file_credit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerRequest) ProtoMessage() {}

func (x *ListLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerRequest.ProtoReflect.Descriptor instead.
func (*ListLedgerRequest) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{5}
}

func (x *ListLedgerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListLedgerRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLedgerRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListLedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LedgerEntry         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Balance       *Balance               `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerResponse) Reset() {
	*x = ListLedgerResponse{}
	mi := &file_credit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerResponse) ProtoMessage() {}

func (x *ListLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerResponse.ProtoReflect.Descriptor instead.
func (*ListLedgerResponse) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{6}
}

func (x *ListLedgerResponse) GetItems() []*LedgerEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListLedgerResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListLedgerResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type GetCheckInStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckInStatusRequest) Reset() {
	*x = GetCheckInStatusRequest{}
	mi := &file_credit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckInStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckInStatusRequest) ProtoMessage() {}

func (x *GetCheckInStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckInStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCheckInStatusRequest) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{7}
}

func (x *GetCheckInStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckInStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckIn       *DailyCheckIn          `protobuf:"bytes,1,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckedIn     bool                   `protobuf:"varint,2,opt,name=checked_in,json=checkedIn,proto3" json:"checked_in,omitempty"`
	RewardCredits int64                  `protobuf:"varint,3,opt,name=reward_credits,json=rewardCredits,proto3" json:"reward_credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInStatusResponse) Reset() {
	*x = CheckInStatusResponse{}
	mi := &file_credit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInStatusResponse) ProtoMessage() {}

func (x *CheckInStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckInStatusResponse) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{8}
}

func (x *CheckInStatusResponse) GetCheckIn() *DailyCheckIn {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *CheckInStatusResponse) GetCheckedIn() bool {
	if x != nil {
		return x.CheckedIn
	}
	return false
}

func (x *CheckInStatusResponse) GetRewardCredits() int64 {
	if x != nil {
		return x.RewardCredits
	}
	return 0
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_credit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{9}
}

func (x *CheckInRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckIn       *DailyCheckIn          `protobuf:"bytes,1,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	Balance       *Balance               `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Ledger        *LedgerEntry           `protobuf:"bytes,3,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Duplicate     bool                   `protobuf:"varint,4,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	RewardCredits int64                  `protobuf:"varint,5,opt,name=reward_credits,json=rewardCredits,proto3" json:"reward_credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_credit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{10}
}

func (x *CheckInResponse) GetCheckIn() *DailyCheckIn {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *CheckInResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *CheckInResponse) GetLedger() *LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *CheckInResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *CheckInResponse) GetRewardCredits() int64 {
	if x != nil {
		return x.RewardCredits
	}
	return 0
}

type DebitCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId string                 `protobuf:"bytes,5,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      int64                  `protobuf:"varint,7,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitCreditsRequest) Reset() {
	*x = DebitCreditsRequest{}
	mi := &file_credit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitCreditsRequest) ProtoMessage() {}

func (x *DebitCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitCreditsRequest.ProtoReflect.Descriptor instead.
func (*DebitCreditsRequest) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{11}
}

func (x *DebitCreditsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DebitCreditsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DebitCreditsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DebitCreditsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DebitCreditsRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *DebitCreditsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *DebitCreditsRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type DebitCreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Ledger        *LedgerEntry           `protobuf:"bytes,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitCreditsResponse) Reset() {
	*x = DebitCreditsResponse{}
	mi := &file_credit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitCreditsResponse) ProtoMessage() {}

func (x *DebitCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitCreditsResponse.ProtoReflect.Descriptor instead.
func (*DebitCreditsResponse) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{12}
}

func (x *DebitCreditsResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *DebitCreditsResponse) GetLedger() *LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *DebitCreditsResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type AdjustCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId string                 `protobuf:"bytes,5,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      int64                  `protobuf:"varint,7,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustCreditsRequest) Reset() {
	*x = AdjustCreditsRequest{}
	mi := &file_credit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustCreditsRequest) ProtoMessage() {}

func (x *AdjustCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustCreditsRequest.ProtoReflect.Descriptor instead.
func (*AdjustCreditsRequest) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{13}
}

func (x *AdjustCreditsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdjustCreditsRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *AdjustCreditsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AdjustCreditsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdjustCreditsRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *AdjustCreditsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AdjustCreditsRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type AdjustCreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Ledger        *LedgerEntry           `protobuf:"bytes,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustCreditsResponse) Reset() {
	*x = AdjustCreditsResponse{}
	mi := &file_credit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustCreditsResponse) ProtoMessage() {}

func (x *AdjustCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustCreditsResponse.ProtoReflect.Descriptor instead.
func (*AdjustCreditsResponse) Descriptor() ([]byte, []int) {
	return file_credit_proto_rawDescGZIP(), []int{14}
}

func (x *AdjustCreditsResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *AdjustCreditsResponse) GetLedger() *LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *AdjustCreditsResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

var File_credit_proto protoreflect.FileDescriptor

const file_credit_proto_rawDesc = "" +
	"\n" +
	"\fcredit.proto\x12\rbbs.credit.v1\"W\n" +
	"\aBalance\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"\xb0\x02\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\x03R\fbalanceAfter\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\a \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\b \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\t \x01(\x03R\bsourceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\xbf\x01\n" +
	"\fDailyCheckIn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"latest_day\x18\x03 \x01(\tR\tlatestDay\x12)\n" +
	"\x10consecutive_days\x18\x04 \x01(\x05R\x0fconsecutiveDays\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"C\n" +
	"\x0fBalanceResponse\x120\n" +
	"\abalance\x18\x01 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\"Z\n" +
	"\x11ListLedgerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x8e\x01\n" +
	"\x12ListLedgerResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.bbs.credit.v1.LedgerEntryR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x120\n" +
	"\abalance\x18\x03 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\"2\n" +
	"\x17GetCheckInStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x95\x01\n" +
	"\x15CheckInStatusResponse\x126\n" +
	"\bcheck_in\x18\x01 \x01(\v2\x1b.bbs.credit.v1.DailyCheckInR\acheckIn\x12\x1d\n" +
	"\n" +
	"checked_in\x18\x02 \x01(\bR\tcheckedIn\x12%\n" +
	"\x0ereward_credits\x18\x03 \x01(\x03R\rrewardCredits\")\n" +
	"\x0eCheckInRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xf4\x01\n" +
	"\x0fCheckInResponse\x126\n" +
	"\bcheck_in\x18\x01 \x01(\v2\x1b.bbs.credit.v1.DailyCheckInR\acheckIn\x120\n" +
	"\abalance\x18\x02 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x122\n" +
	"\x06ledger\x18\x03 \x01(\v2\x1a.bbs.credit.v1.LedgerEntryR\x06ledger\x12\x1c\n" +
	"\tduplicate\x18\x04 \x01(\bR\tduplicate\x12%\n" +
	"\x0ereward_credits\x18\x05 \x01(\x03R\rrewardCredits\"\xe6\x01\n" +
	"\x13DebitCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\x05 \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\a \x01(\x03R\bsourceId\"\x9a\x01\n" +
	"\x14DebitCreditsResponse\x120\n" +
	"\abalance\x18\x01 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x122\n" +
	"\x06ledger\x18\x02 \x01(\v2\x1a.bbs.credit.v1.LedgerEntryR\x06ledger\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\"\xe5\x01\n" +
	"\x14AdjustCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\x05 \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\a \x01(\x03R\bsourceId\"\x9b\x01\n" +
	"\x15AdjustCreditsResponse\x120\n" +
	"\abalance\x18\x01 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x122\n" +
	"\x06ledger\x18\x02 \x01(\v2\x1a.bbs.credit.v1.LedgerEntryR\x06ledger\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate2\x93\x04\n" +
	"\rCreditService\x12N\n" +
	"\n" +
	"GetBalance\x12 .bbs.credit.v1.GetBalanceRequest\x1a\x1e.bbs.credit.v1.BalanceResponse\x12Q\n" +
	"\n" +
	"ListLedger\x12 .bbs.credit.v1.ListLedgerRequest\x1a!.bbs.credit.v1.ListLedgerResponse\x12`\n" +
	"\x10GetCheckInStatus\x12&.bbs.credit.v1.GetCheckInStatusRequest\x1a$.bbs.credit.v1.CheckInStatusResponse\x12H\n" +
	"\aCheckIn\x12\x1d.bbs.credit.v1.CheckInRequest\x1a\x1e.bbs.credit.v1.CheckInResponse\x12W\n" +
	"\fDebitCredits\x12\".bbs.credit.v1.DebitCreditsRequest\x1a#.bbs.credit.v1.DebitCreditsResponse\x12Z\n" +
	"\rAdjustCredits\x12#.bbs.credit.v1.AdjustCreditsRequest\x1a$.bbs.credit.v1.AdjustCreditsResponseB)Z'api-gateway/api/proto/creditpb;creditpbb\x06proto3"

var (
	file_credit_proto_rawDescOnce sync.Once
	file_credit_proto_rawDescData []byte
)

func file_credit_proto_rawDescGZIP() []byte {
	file_credit_proto_rawDescOnce.Do(func() {
		file_credit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credit_proto_rawDesc), len(file_credit_proto_rawDesc)))
	})
	return file_credit_proto_rawDescData
}

var file_credit_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_credit_proto_goTypes = []any{
	(*Balance)(nil),                 // 0: bbs.credit.v1.Balance
	(*LedgerEntry)(nil),             // 1: bbs.credit.v1.LedgerEntry
	(*DailyCheckIn)(nil),            // 2: bbs.credit.v1.DailyCheckIn
	(*GetBalanceRequest)(nil),       // 3: bbs.credit.v1.GetBalanceRequest
	(*BalanceResponse)(nil),         // 4: bbs.credit.v1.BalanceResponse
	(*ListLedgerRequest)(nil),       // 5: bbs.credit.v1.ListLedgerRequest
	(*ListLedgerResponse)(nil),      // 6: bbs.credit.v1.ListLedgerResponse
	(*GetCheckInStatusRequest)(nil), // 7: bbs.credit.v1.GetCheckInStatusRequest
	(*CheckInStatusResponse)(nil),   // 8: bbs.credit.v1.CheckInStatusResponse
	(*CheckInRequest)(nil),          // 9: bbs.credit.v1.CheckInRequest
	(*CheckInResponse)(nil),         // 10: bbs.credit.v1.CheckInResponse
	(*DebitCreditsRequest)(nil),     // 11: bbs.credit.v1.DebitCreditsRequest
	(*DebitCreditsResponse)(nil),    // 12: bbs.credit.v1.DebitCreditsResponse
	(*AdjustCreditsRequest)(nil),    // 13: bbs.credit.v1.AdjustCreditsRequest
	(*AdjustCreditsResponse)(nil),   // 14: bbs.credit.v1.AdjustCreditsResponse
}
var file_credit_proto_depIdxs = []int32{
	0,  // 0: bbs.credit.v1.BalanceResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 1: bbs.credit.v1.ListLedgerResponse.items:type_name -> bbs.credit.v1.LedgerEntry
	0,  // 2: bbs.credit.v1.ListLedgerResponse.balance:type_name -> bbs.credit.v1.Balance
	2,  // 3: bbs.credit.v1.CheckInStatusResponse.check_in:type_name -> bbs.credit.v1.DailyCheckIn
	2,  // 4: bbs.credit.v1.CheckInResponse.check_in:type_name -> bbs.credit.v1.DailyCheckIn
	0,  // 5: bbs.credit.v1.CheckInResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 6: bbs.credit.v1.CheckInResponse.ledger:type_name -> bbs.credit.v1.LedgerEntry
	0,  // 7: bbs.credit.v1.DebitCreditsResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 8: bbs.credit.v1.DebitCreditsResponse.ledger:type_name -> bbs.credit.v1.LedgerEntry
	0,  // 9: bbs.credit.v1.AdjustCreditsResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 10: bbs.credit.v1.AdjustCreditsResponse.ledger:type_name -> bbs.credit.v1.LedgerEntry
	3,  // 11: bbs.credit.v1.CreditService.GetBalance:input_type -> bbs.credit.v1.GetBalanceRequest
	5,  // 12: bbs.credit.v1.CreditService.ListLedger:input_type -> bbs.credit.v1.ListLedgerRequest
	7,  // 13: bbs.credit.v1.CreditService.GetCheckInStatus:input_type -> bbs.credit.v1.GetCheckInStatusRequest
	9,  // 14: bbs.credit.v1.CreditService.CheckIn:input_type -> bbs.credit.v1.CheckInRequest
	11, // 15: bbs.credit.v1.CreditService.DebitCredits:input_type -> bbs.credit.v1.DebitCreditsRequest
	13, // 16: bbs.credit.v1.CreditService.AdjustCredits:input_type -> bbs.credit.v1.AdjustCreditsRequest
	4,  // 17: bbs.credit.v1.CreditService.GetBalance:output_type -> bbs.credit.v1.BalanceResponse
	6,  // 18: bbs.credit.v1.CreditService.ListLedger:output_type -> bbs.credit.v1.ListLedgerResponse
	8,  // 19: bbs.credit.v1.CreditService.GetCheckInStatus:output_type -> bbs.credit.v1.CheckInStatusResponse
	10, // 20: bbs.credit.v1.CreditService.CheckIn:output_type -> bbs.credit.v1.CheckInResponse
	12, // 21: bbs.credit.v1.CreditService.DebitCredits:output_type -> bbs.credit.v1.DebitCreditsResponse
	14, // 22: bbs.credit.v1.CreditService.AdjustCredits:output_type -> bbs.credit.v1.AdjustCreditsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_credit_proto_init() }
func file_credit_proto_init() {
	if File_credit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credit_proto_rawDesc), len(file_credit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credit_proto_goTypes,
		DependencyIndexes: file_credit_proto_depIdxs,
		MessageInfos:      file_credit_proto_msgTypes,
	}.Build()
	File_credit_proto = out.File
	file_credit_proto_goTypes = nil
	file_credit_proto_depIdxs = nil
}
