// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.1
// source: api/proto/credit.proto

package creditpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CreditService_GetBalance_FullMethodName            = "/bbs.credit.v1.CreditService/GetBalance"
	CreditService_ListLedger_FullMethodName            = "/bbs.credit.v1.CreditService/ListLedger"
	CreditService_ListLeaderboard_FullMethodName       = "/bbs.credit.v1.CreditService/ListLeaderboard"
	CreditService_GetCheckInStatus_FullMethodName      = "/bbs.credit.v1.CreditService/GetCheckInStatus"
	CreditService_CheckIn_FullMethodName               = "/bbs.credit.v1.CreditService/CheckIn"
	CreditService_GetTaskClaimStatus_FullMethodName    = "/bbs.credit.v1.CreditService/GetTaskClaimStatus"
	CreditService_ListTaskClaimStatuses_FullMethodName = "/bbs.credit.v1.CreditService/ListTaskClaimStatuses"
	CreditService_ClaimTask_FullMethodName             = "/bbs.credit.v1.CreditService/ClaimTask"
	CreditService_DebitCredits_FullMethodName          = "/bbs.credit.v1.CreditService/DebitCredits"
	CreditService_AdjustCredits_FullMethodName         = "/bbs.credit.v1.CreditService/AdjustCredits"
	CreditService_TransferCredits_FullMethodName       = "/bbs.credit.v1.CreditService/TransferCredits"
	CreditService_ReserveCredits_FullMethodName        = "/bbs.credit.v1.CreditService/ReserveCredits"
	CreditService_ReleaseCredits_FullMethodName        = "/bbs.credit.v1.CreditService/ReleaseCredits"
	CreditService_ReverseQAAcceptance_FullMethodName   = "/bbs.credit.v1.CreditService/ReverseQAAcceptance"
	CreditService_EraseUserData_FullMethodName         = "/bbs.credit.v1.CreditService/EraseUserData"
)

// CreditServiceClient is the client API for CreditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreditServiceClient interface {
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	ListLedger(ctx context.Context, in *ListLedgerRequest, opts ...grpc.CallOption) (*ListLedgerResponse, error)
	ListLeaderboard(ctx context.Context, in *ListLeaderboardRequest, opts ...grpc.CallOption) (*ListLeaderboardResponse, error)
	GetCheckInStatus(ctx context.Context, in *GetCheckInStatusRequest, opts ...grpc.CallOption) (*CheckInStatusResponse, error)
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
	GetTaskClaimStatus(ctx context.Context, in *GetTaskClaimStatusRequest, opts ...grpc.CallOption) (*TaskClaimStatusResponse, error)
	ListTaskClaimStatuses(ctx context.Context, in *ListTaskClaimStatusesRequest, opts ...grpc.CallOption) (*ListTaskClaimStatusesResponse, error)
	ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*ClaimTaskResponse, error)
	DebitCredits(ctx context.Context, in *DebitCreditsRequest, opts ...grpc.CallOption) (*DebitCreditsResponse, error)
	AdjustCredits(ctx context.Context, in *AdjustCreditsRequest, opts ...grpc.CallOption) (*AdjustCreditsResponse, error)
	TransferCredits(ctx context.Context, in *TransferCreditsRequest, opts ...grpc.CallOption) (*TransferCreditsResponse, error)
	ReserveCredits(ctx context.Context, in *ReserveCreditsRequest, opts ...grpc.CallOption) (*ReserveCreditsResponse, error)
	ReleaseCredits(ctx context.Context, in *ReleaseCreditsRequest, opts ...grpc.CallOption) (*ReleaseCreditsResponse, error)
	ReverseQAAcceptance(ctx context.Context, in *ReverseQAAcceptanceRequest, opts ...grpc.CallOption) (*ReverseQAAcceptanceResponse, error)
	EraseUserData(ctx context.Context, in *EraseUserDataRequest, opts ...grpc.CallOption) (*EraseUserDataResponse, error)
}

type creditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreditServiceClient(cc grpc.ClientConnInterface) CreditServiceClient {
	return &creditServiceClient{cc}
}

func (c *creditServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, CreditService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ListLedger(ctx context.Context, in *ListLedgerRequest, opts ...grpc.CallOption) (*ListLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLedgerResponse)
	err := c.cc.Invoke(ctx, CreditService_ListLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ListLeaderboard(ctx context.Context, in *ListLeaderboardRequest, opts ...grpc.CallOption) (*ListLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeaderboardResponse)
	err := c.cc.Invoke(ctx, CreditService_ListLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) GetCheckInStatus(ctx context.Context, in *GetCheckInStatusRequest, opts ...grpc.CallOption) (*CheckInStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInStatusResponse)
	err := c.cc.Invoke(ctx, CreditService_GetCheckInStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, CreditService_CheckIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) GetTaskClaimStatus(ctx context.Context, in *GetTaskClaimStatusRequest, opts ...grpc.CallOption) (*TaskClaimStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskClaimStatusResponse)
	err := c.cc.Invoke(ctx, CreditService_GetTaskClaimStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ListTaskClaimStatuses(ctx context.Context, in *ListTaskClaimStatusesRequest, opts ...grpc.CallOption) (*ListTaskClaimStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaskClaimStatusesResponse)
	err := c.cc.Invoke(ctx, CreditService_ListTaskClaimStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*ClaimTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimTaskResponse)
	err := c.cc.Invoke(ctx, CreditService_ClaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) DebitCredits(ctx context.Context, in *DebitCreditsRequest, opts ...grpc.CallOption) (*DebitCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebitCreditsResponse)
	err := c.cc.Invoke(ctx, CreditService_DebitCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) AdjustCredits(ctx context.Context, in *AdjustCreditsRequest, opts ...grpc.CallOption) (*AdjustCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustCreditsResponse)
	err := c.cc.Invoke(ctx, CreditService_AdjustCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) TransferCredits(ctx context.Context, in *TransferCreditsRequest, opts ...grpc.CallOption) (*TransferCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferCreditsResponse)
	err := c.cc.Invoke(ctx, CreditService_TransferCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ReserveCredits(ctx context.Context, in *ReserveCreditsRequest, opts ...grpc.CallOption) (*ReserveCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveCreditsResponse)
	err := c.cc.Invoke(ctx, CreditService_ReserveCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ReleaseCredits(ctx context.Context, in *ReleaseCreditsRequest, opts ...grpc.CallOption) (*ReleaseCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseCreditsResponse)
	err := c.cc.Invoke(ctx, CreditService_ReleaseCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) ReverseQAAcceptance(ctx context.Context, in *ReverseQAAcceptanceRequest, opts ...grpc.CallOption) (*ReverseQAAcceptanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseQAAcceptanceResponse)
	err := c.cc.Invoke(ctx, CreditService_ReverseQAAcceptance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditServiceClient) EraseUserData(ctx context.Context, in *EraseUserDataRequest, opts ...grpc.CallOption) (*EraseUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EraseUserDataResponse)
	err := c.cc.Invoke(ctx, CreditService_EraseUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreditServiceServer is the server API for CreditService service.
// All implementations must embed UnimplementedCreditServiceServer
// for forward compatibility.
type CreditServiceServer interface {
	GetBalance(context.Context, *GetBalanceRequest) (*BalanceResponse, error)
	ListLedger(context.Context, *ListLedgerRequest) (*ListLedgerResponse, error)
	ListLeaderboard(context.Context, *ListLeaderboardRequest) (*ListLeaderboardResponse, error)
	GetCheckInStatus(context.Context, *GetCheckInStatusRequest) (*CheckInStatusResponse, error)
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
	GetTaskClaimStatus(context.Context, *GetTaskClaimStatusRequest) (*TaskClaimStatusResponse, error)
	ListTaskClaimStatuses(context.Context, *ListTaskClaimStatusesRequest) (*ListTaskClaimStatusesResponse, error)
	ClaimTask(context.Context, *ClaimTaskRequest) (*ClaimTaskResponse, error)
	DebitCredits(context.Context, *DebitCreditsRequest) (*DebitCreditsResponse, error)
	AdjustCredits(context.Context, *AdjustCreditsRequest) (*AdjustCreditsResponse, error)
	TransferCredits(context.Context, *TransferCreditsRequest) (*TransferCreditsResponse, error)
	ReserveCredits(context.Context, *ReserveCreditsRequest) (*ReserveCreditsResponse, error)
	ReleaseCredits(context.Context, *ReleaseCreditsRequest) (*ReleaseCreditsResponse, error)
	ReverseQAAcceptance(context.Context, *ReverseQAAcceptanceRequest) (*ReverseQAAcceptanceResponse, error)
	EraseUserData(context.Context, *EraseUserDataRequest) (*EraseUserDataResponse, error)
	mustEmbedUnimplementedCreditServiceServer()
}

// UnimplementedCreditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCreditServiceServer struct{}

func (UnimplementedCreditServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedCreditServiceServer) ListLedger(context.Context, *ListLedgerRequest) (*ListLedgerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLedger not implemented")
}
func (UnimplementedCreditServiceServer) ListLeaderboard(context.Context, *ListLeaderboardRequest) (*ListLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeaderboard not implemented")
}
func (UnimplementedCreditServiceServer) GetCheckInStatus(context.Context, *GetCheckInStatusRequest) (*CheckInStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckInStatus not implemented")
}
func (UnimplementedCreditServiceServer) CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIn not implemented")
}
func (UnimplementedCreditServiceServer) GetTaskClaimStatus(context.Context, *GetTaskClaimStatusRequest) (*TaskClaimStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskClaimStatus not implemented")
}
func (UnimplementedCreditServiceServer) ListTaskClaimStatuses(context.Context, *ListTaskClaimStatusesRequest) (*ListTaskClaimStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaskClaimStatuses not implemented")
}
func (UnimplementedCreditServiceServer) ClaimTask(context.Context, *ClaimTaskRequest) (*ClaimTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimTask not implemented")
}
func (UnimplementedCreditServiceServer) DebitCredits(context.Context, *DebitCreditsRequest) (*DebitCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebitCredits not implemented")
}
func (UnimplementedCreditServiceServer) AdjustCredits(context.Context, *AdjustCreditsRequest) (*AdjustCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustCredits not implemented")
}
func (UnimplementedCreditServiceServer) TransferCredits(context.Context, *TransferCreditsRequest) (*TransferCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferCredits not implemented")
}
func (UnimplementedCreditServiceServer) ReserveCredits(context.Context, *ReserveCreditsRequest) (*ReserveCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveCredits not implemented")
}
func (UnimplementedCreditServiceServer) ReleaseCredits(context.Context, *ReleaseCreditsRequest) (*ReleaseCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseCredits not implemented")
}
func (UnimplementedCreditServiceServer) ReverseQAAcceptance(context.Context, *ReverseQAAcceptanceRequest) (*ReverseQAAcceptanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseQAAcceptance not implemented")
}
func (UnimplementedCreditServiceServer) EraseUserData(context.Context, *EraseUserDataRequest) (*EraseUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EraseUserData not implemented")
}
func (UnimplementedCreditServiceServer) mustEmbedUnimplementedCreditServiceServer() {}
func (UnimplementedCreditServiceServer) testEmbeddedByValue()                       {}

// UnsafeCreditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreditServiceServer will
// result in compilation errors.
type UnsafeCreditServiceServer interface {
	mustEmbedUnimplementedCreditServiceServer()
}

func RegisterCreditServiceServer(s grpc.ServiceRegistrar, srv CreditServiceServer) {
	// If the following call panics, it indicates UnimplementedCreditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CreditService_ServiceDesc, srv)
}

func _CreditService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ListLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ListLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ListLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ListLedger(ctx, req.(*ListLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ListLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ListLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ListLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ListLeaderboard(ctx, req.(*ListLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_GetCheckInStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckInStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetCheckInStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetCheckInStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetCheckInStatus(ctx, req.(*GetCheckInStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_CheckIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_GetTaskClaimStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskClaimStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).GetTaskClaimStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_GetTaskClaimStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).GetTaskClaimStatus(ctx, req.(*GetTaskClaimStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ListTaskClaimStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskClaimStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ListTaskClaimStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ListTaskClaimStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ListTaskClaimStatuses(ctx, req.(*ListTaskClaimStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ClaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ClaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ClaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ClaimTask(ctx, req.(*ClaimTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_DebitCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).DebitCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_DebitCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).DebitCredits(ctx, req.(*DebitCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_AdjustCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).AdjustCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_AdjustCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).AdjustCredits(ctx, req.(*AdjustCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_TransferCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).TransferCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_TransferCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).TransferCredits(ctx, req.(*TransferCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ReserveCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ReserveCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ReserveCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ReserveCredits(ctx, req.(*ReserveCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ReleaseCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ReleaseCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ReleaseCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ReleaseCredits(ctx, req.(*ReleaseCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_ReverseQAAcceptance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseQAAcceptanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).ReverseQAAcceptance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_ReverseQAAcceptance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).ReverseQAAcceptance(ctx, req.(*ReverseQAAcceptanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditService_EraseUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EraseUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditServiceServer).EraseUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CreditService_EraseUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditServiceServer).EraseUserData(ctx, req.(*EraseUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreditService_ServiceDesc is the grpc.ServiceDesc for CreditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bbs.credit.v1.CreditService",
	HandlerType: (*CreditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _CreditService_GetBalance_Handler,
		},
		{
			MethodName: "ListLedger",
			Handler:    _CreditService_ListLedger_Handler,
		},
		{
			MethodName: "ListLeaderboard",
			Handler:    _CreditService_ListLeaderboard_Handler,
		},
		{
			MethodName: "GetCheckInStatus",
			Handler:    _CreditService_GetCheckInStatus_Handler,
		},
		{
			MethodName: "CheckIn",
			Handler:    _CreditService_CheckIn_Handler,
		},
		{
			MethodName: "GetTaskClaimStatus",
			Handler:    _CreditService_GetTaskClaimStatus_Handler,
		},
		{
			MethodName: "ListTaskClaimStatuses",
			Handler:    _CreditService_ListTaskClaimStatuses_Handler,
		},
		{
			MethodName: "ClaimTask",
			Handler:    _CreditService_ClaimTask_Handler,
		},
		{
			MethodName: "DebitCredits",
			Handler:    _CreditService_DebitCredits_Handler,
		},
		{
			MethodName: "AdjustCredits",
			Handler:    _CreditService_AdjustCredits_Handler,
		},
		{
			MethodName: "TransferCredits",
			Handler:    _CreditService_TransferCredits_Handler,
		},
		{
			MethodName: "ReserveCredits",
			Handler:    _CreditService_ReserveCredits_Handler,
		},
		{
			MethodName: "ReleaseCredits",
			Handler:    _CreditService_ReleaseCredits_Handler,
		},
		{
			MethodName: "ReverseQAAcceptance",
			Handler:    _CreditService_ReverseQAAcceptance_Handler,
		},
		{
			MethodName: "EraseUserData",
			Handler:    _CreditService_EraseUserData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/credit.proto",
}
