// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/proto/credit.proto

package creditpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_api_proto_credit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{0}
}

func (x *Balance) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Balance) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Balance) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,4,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId string                 `protobuf:"bytes,7,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,8,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      int64                  `protobuf:"varint,9,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_api_proto_credit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerEntry) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LedgerEntry) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *LedgerEntry) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *LedgerEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LedgerEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LedgerEntry) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *LedgerEntry) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *LedgerEntry) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *LedgerEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DailyCheckIn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LatestDay       string                 `protobuf:"bytes,3,opt,name=latest_day,json=latestDay,proto3" json:"latest_day,omitempty"`
	ConsecutiveDays int32                  `protobuf:"varint,4,opt,name=consecutive_days,json=consecutiveDays,proto3" json:"consecutive_days,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyCheckIn) Reset() {
	*x = DailyCheckIn{}
	mi := &file_api_proto_credit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyCheckIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyCheckIn) ProtoMessage() {}

func (x *DailyCheckIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyCheckIn.ProtoReflect.Descriptor instead.
func (*DailyCheckIn) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{2}
}

func (x *DailyCheckIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DailyCheckIn) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DailyCheckIn) GetLatestDay() string {
	if x != nil {
		return x.LatestDay
	}
	return ""
}

func (x *DailyCheckIn) GetConsecutiveDays() int32 {
	if x != nil {
		return x.ConsecutiveDays
	}
	return 0
}

func (x *DailyCheckIn) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DailyCheckIn) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreditReservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId string                 `protobuf:"bytes,7,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,8,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      int64                  `protobuf:"varint,9,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SettledAt     int64                  `protobuf:"varint,12,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditReservation) Reset() {
	*x = CreditReservation{}
	mi := &file_api_proto_credit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditReservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditReservation) ProtoMessage() {}

func (x *CreditReservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditReservation.ProtoReflect.Descriptor instead.
func (*CreditReservation) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{3}
}

func (x *CreditReservation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreditReservation) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreditReservation) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreditReservation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreditReservation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreditReservation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreditReservation) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *CreditReservation) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CreditReservation) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *CreditReservation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreditReservation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CreditReservation) GetSettledAt() int64 {
	if x != nil {
		return x.SettledAt
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type ListLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerRequest) Reset() {
	*x = ListLedgerRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerRequest) ProtoMessage() {}

func (x *ListLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerRequest.ProtoReflect.Descriptor instead.
func (*ListLedgerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{6}
}

func (x *ListLedgerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListLedgerRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLedgerRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListLedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LedgerEntry         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Balance       *Balance               `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLedgerResponse) Reset() {
	*x = ListLedgerResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLedgerResponse) ProtoMessage() {}

func (x *ListLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLedgerResponse.ProtoReflect.Descriptor instead.
func (*ListLedgerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{7}
}

func (x *ListLedgerResponse) GetItems() []*LedgerEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListLedgerResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListLedgerResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type GetCheckInStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckInStatusRequest) Reset() {
	*x = GetCheckInStatusRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckInStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckInStatusRequest) ProtoMessage() {}

func (x *GetCheckInStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckInStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCheckInStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{8}
}

func (x *GetCheckInStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckInStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckIn       *DailyCheckIn          `protobuf:"bytes,1,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckedIn     bool                   `protobuf:"varint,2,opt,name=checked_in,json=checkedIn,proto3" json:"checked_in,omitempty"`
	RewardCredits int64                  `protobuf:"varint,3,opt,name=reward_credits,json=rewardCredits,proto3" json:"reward_credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInStatusResponse) Reset() {
	*x = CheckInStatusResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInStatusResponse) ProtoMessage() {}

func (x *CheckInStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckInStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{9}
}

func (x *CheckInStatusResponse) GetCheckIn() *DailyCheckIn {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *CheckInStatusResponse) GetCheckedIn() bool {
	if x != nil {
		return x.CheckedIn
	}
	return false
}

func (x *CheckInStatusResponse) GetRewardCredits() int64 {
	if x != nil {
		return x.RewardCredits
	}
	return 0
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{10}
}

func (x *CheckInRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckIn       *DailyCheckIn          `protobuf:"bytes,1,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	Balance       *Balance               `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Ledger        *LedgerEntry           `protobuf:"bytes,3,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Duplicate     bool                   `protobuf:"varint,4,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	RewardCredits int64                  `protobuf:"varint,5,opt,name=reward_credits,json=rewardCredits,proto3" json:"reward_credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{11}
}

func (x *CheckInResponse) GetCheckIn() *DailyCheckIn {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *CheckInResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *CheckInResponse) GetLedger() *LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *CheckInResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *CheckInResponse) GetRewardCredits() int64 {
	if x != nil {
		return x.RewardCredits
	}
	return 0
}

type TaskClaimStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskKey       string                 `protobuf:"bytes,2,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	Cycle         string                 `protobuf:"bytes,3,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Completed     bool                   `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	Claimed       bool                   `protobuf:"varint,5,opt,name=claimed,proto3" json:"claimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskClaimStatus) Reset() {
	*x = TaskClaimStatus{}
	mi := &file_api_proto_credit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskClaimStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClaimStatus) ProtoMessage() {}

func (x *TaskClaimStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClaimStatus.ProtoReflect.Descriptor instead.
func (*TaskClaimStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{12}
}

func (x *TaskClaimStatus) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskClaimStatus) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *TaskClaimStatus) GetCycle() string {
	if x != nil {
		return x.Cycle
	}
	return ""
}

func (x *TaskClaimStatus) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *TaskClaimStatus) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

type GetTaskClaimStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskKey       string                 `protobuf:"bytes,3,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskClaimStatusRequest) Reset() {
	*x = GetTaskClaimStatusRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskClaimStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskClaimStatusRequest) ProtoMessage() {}

func (x *GetTaskClaimStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskClaimStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskClaimStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{13}
}

func (x *GetTaskClaimStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTaskClaimStatusRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskClaimStatusRequest) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

type TaskClaimStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *TaskClaimStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskClaimStatusResponse) Reset() {
	*x = TaskClaimStatusResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskClaimStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClaimStatusResponse) ProtoMessage() {}

func (x *TaskClaimStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClaimStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskClaimStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{14}
}

func (x *TaskClaimStatusResponse) GetStatus() *TaskClaimStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type TaskClaimStatusInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskKey       string                 `protobuf:"bytes,2,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskClaimStatusInput) Reset() {
	*x = TaskClaimStatusInput{}
	mi := &file_api_proto_credit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskClaimStatusInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskClaimStatusInput) ProtoMessage() {}

func (x *TaskClaimStatusInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskClaimStatusInput.ProtoReflect.Descriptor instead.
func (*TaskClaimStatusInput) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{15}
}

func (x *TaskClaimStatusInput) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskClaimStatusInput) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

type ListTaskClaimStatusesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserId        int64                   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tasks         []*TaskClaimStatusInput `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskClaimStatusesRequest) Reset() {
	*x = ListTaskClaimStatusesRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskClaimStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskClaimStatusesRequest) ProtoMessage() {}

func (x *ListTaskClaimStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskClaimStatusesRequest.ProtoReflect.Descriptor instead.
func (*ListTaskClaimStatusesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{16}
}

func (x *ListTaskClaimStatusesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTaskClaimStatusesRequest) GetTasks() []*TaskClaimStatusInput {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ListTaskClaimStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TaskClaimStatus     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskClaimStatusesResponse) Reset() {
	*x = ListTaskClaimStatusesResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskClaimStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskClaimStatusesResponse) ProtoMessage() {}

func (x *ListTaskClaimStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskClaimStatusesResponse.ProtoReflect.Descriptor instead.
func (*ListTaskClaimStatusesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{17}
}

func (x *ListTaskClaimStatusesResponse) GetItems() []*TaskClaimStatus {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClaimTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskKey       string                 `protobuf:"bytes,3,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	RewardCredits int64                  `protobuf:"varint,4,opt,name=reward_credits,json=rewardCredits,proto3" json:"reward_credits,omitempty"`
	TaskTitle     string                 `protobuf:"bytes,5,opt,name=task_title,json=taskTitle,proto3" json:"task_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskRequest) Reset() {
	*x = ClaimTaskRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRequest) ProtoMessage() {}

func (x *ClaimTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRequest.ProtoReflect.Descriptor instead.
func (*ClaimTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{18}
}

func (x *ClaimTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ClaimTaskRequest) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *ClaimTaskRequest) GetRewardCredits() int64 {
	if x != nil {
		return x.RewardCredits
	}
	return 0
}

func (x *ClaimTaskRequest) GetTaskTitle() string {
	if x != nil {
		return x.TaskTitle
	}
	return ""
}

type ClaimTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *TaskClaimStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Balance       *Balance               `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Ledger        *LedgerEntry           `protobuf:"bytes,3,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Duplicate     bool                   `protobuf:"varint,4,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskResponse) Reset() {
	*x = ClaimTaskResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskResponse) ProtoMessage() {}

func (x *ClaimTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskResponse.ProtoReflect.Descriptor instead.
func (*ClaimTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{19}
}

func (x *ClaimTaskResponse) GetStatus() *TaskClaimStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ClaimTaskResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *ClaimTaskResponse) GetLedger() *LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *ClaimTaskResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type DebitCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId string                 `protobuf:"bytes,5,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      int64                  `protobuf:"varint,7,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitCreditsRequest) Reset() {
	*x = DebitCreditsRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitCreditsRequest) ProtoMessage() {}

func (x *DebitCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitCreditsRequest.ProtoReflect.Descriptor instead.
func (*DebitCreditsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{20}
}

func (x *DebitCreditsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DebitCreditsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DebitCreditsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DebitCreditsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DebitCreditsRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *DebitCreditsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *DebitCreditsRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type DebitCreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Ledger        *LedgerEntry           `protobuf:"bytes,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitCreditsResponse) Reset() {
	*x = DebitCreditsResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitCreditsResponse) ProtoMessage() {}

func (x *DebitCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitCreditsResponse.ProtoReflect.Descriptor instead.
func (*DebitCreditsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{21}
}

func (x *DebitCreditsResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *DebitCreditsResponse) GetLedger() *LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *DebitCreditsResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type AdjustCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId string                 `protobuf:"bytes,5,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      int64                  `protobuf:"varint,7,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustCreditsRequest) Reset() {
	*x = AdjustCreditsRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustCreditsRequest) ProtoMessage() {}

func (x *AdjustCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustCreditsRequest.ProtoReflect.Descriptor instead.
func (*AdjustCreditsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{22}
}

func (x *AdjustCreditsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdjustCreditsRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *AdjustCreditsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AdjustCreditsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdjustCreditsRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *AdjustCreditsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AdjustCreditsRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type AdjustCreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Ledger        *LedgerEntry           `protobuf:"bytes,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustCreditsResponse) Reset() {
	*x = AdjustCreditsResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustCreditsResponse) ProtoMessage() {}

func (x *AdjustCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustCreditsResponse.ProtoReflect.Descriptor instead.
func (*AdjustCreditsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{23}
}

func (x *AdjustCreditsResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *AdjustCreditsResponse) GetLedger() *LedgerEntry {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *AdjustCreditsResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type TransferCreditsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PayerUserId       int64                  `protobuf:"varint,1,opt,name=payer_user_id,json=payerUserId,proto3" json:"payer_user_id,omitempty"`
	PayeeUserId       int64                  `protobuf:"varint,2,opt,name=payee_user_id,json=payeeUserId,proto3" json:"payee_user_id,omitempty"`
	Amount            int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	DebitReason       string                 `protobuf:"bytes,4,opt,name=debit_reason,json=debitReason,proto3" json:"debit_reason,omitempty"`
	DebitDescription  string                 `protobuf:"bytes,5,opt,name=debit_description,json=debitDescription,proto3" json:"debit_description,omitempty"`
	CreditReason      string                 `protobuf:"bytes,6,opt,name=credit_reason,json=creditReason,proto3" json:"credit_reason,omitempty"`
	CreditDescription string                 `protobuf:"bytes,7,opt,name=credit_description,json=creditDescription,proto3" json:"credit_description,omitempty"`
	SourceEventId     string                 `protobuf:"bytes,8,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType        string                 `protobuf:"bytes,9,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId          int64                  `protobuf:"varint,10,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransferCreditsRequest) Reset() {
	*x = TransferCreditsRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCreditsRequest) ProtoMessage() {}

func (x *TransferCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCreditsRequest.ProtoReflect.Descriptor instead.
func (*TransferCreditsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{24}
}

func (x *TransferCreditsRequest) GetPayerUserId() int64 {
	if x != nil {
		return x.PayerUserId
	}
	return 0
}

func (x *TransferCreditsRequest) GetPayeeUserId() int64 {
	if x != nil {
		return x.PayeeUserId
	}
	return 0
}

func (x *TransferCreditsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferCreditsRequest) GetDebitReason() string {
	if x != nil {
		return x.DebitReason
	}
	return ""
}

func (x *TransferCreditsRequest) GetDebitDescription() string {
	if x != nil {
		return x.DebitDescription
	}
	return ""
}

func (x *TransferCreditsRequest) GetCreditReason() string {
	if x != nil {
		return x.CreditReason
	}
	return ""
}

func (x *TransferCreditsRequest) GetCreditDescription() string {
	if x != nil {
		return x.CreditDescription
	}
	return ""
}

func (x *TransferCreditsRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *TransferCreditsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *TransferCreditsRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type TransferCreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferCreditsResponse) Reset() {
	*x = TransferCreditsResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCreditsResponse) ProtoMessage() {}

func (x *TransferCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCreditsResponse.ProtoReflect.Descriptor instead.
func (*TransferCreditsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{25}
}

type ReserveCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId string                 `protobuf:"bytes,5,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      int64                  `protobuf:"varint,7,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCreditsRequest) Reset() {
	*x = ReserveCreditsRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCreditsRequest) ProtoMessage() {}

func (x *ReserveCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCreditsRequest.ProtoReflect.Descriptor instead.
func (*ReserveCreditsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{26}
}

func (x *ReserveCreditsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveCreditsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReserveCreditsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReserveCreditsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReserveCreditsRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *ReserveCreditsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ReserveCreditsRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type ReserveCreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Reservation   *CreditReservation     `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCreditsResponse) Reset() {
	*x = ReserveCreditsResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCreditsResponse) ProtoMessage() {}

func (x *ReserveCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCreditsResponse.ProtoReflect.Descriptor instead.
func (*ReserveCreditsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{27}
}

func (x *ReserveCreditsResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *ReserveCreditsResponse) GetReservation() *CreditReservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

func (x *ReserveCreditsResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type ReleaseCreditsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount            int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ReservationReason string                 `protobuf:"bytes,3,opt,name=reservation_reason,json=reservationReason,proto3" json:"reservation_reason,omitempty"`
	ReleaseReason     string                 `protobuf:"bytes,4,opt,name=release_reason,json=releaseReason,proto3" json:"release_reason,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	SourceEventId     string                 `protobuf:"bytes,6,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	SourceType        string                 `protobuf:"bytes,7,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId          int64                  `protobuf:"varint,8,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReleaseCreditsRequest) Reset() {
	*x = ReleaseCreditsRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCreditsRequest) ProtoMessage() {}

func (x *ReleaseCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCreditsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseCreditsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{28}
}

func (x *ReleaseCreditsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReleaseCreditsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReleaseCreditsRequest) GetReservationReason() string {
	if x != nil {
		return x.ReservationReason
	}
	return ""
}

func (x *ReleaseCreditsRequest) GetReleaseReason() string {
	if x != nil {
		return x.ReleaseReason
	}
	return ""
}

func (x *ReleaseCreditsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReleaseCreditsRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *ReleaseCreditsRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ReleaseCreditsRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type ReleaseCreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Reservation   *CreditReservation     `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	Duplicate     bool                   `protobuf:"varint,3,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCreditsResponse) Reset() {
	*x = ReleaseCreditsResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCreditsResponse) ProtoMessage() {}

func (x *ReleaseCreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCreditsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseCreditsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{29}
}

func (x *ReleaseCreditsResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *ReleaseCreditsResponse) GetReservation() *CreditReservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

func (x *ReleaseCreditsResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type ReverseQAAcceptanceRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	QuestionAuthorId        int64                  `protobuf:"varint,1,opt,name=question_author_id,json=questionAuthorId,proto3" json:"question_author_id,omitempty"`
	TopicId                 int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	AcceptedCommentId       int64                  `protobuf:"varint,3,opt,name=accepted_comment_id,json=acceptedCommentId,proto3" json:"accepted_comment_id,omitempty"`
	AcceptedCommentAuthorId int64                  `protobuf:"varint,4,opt,name=accepted_comment_author_id,json=acceptedCommentAuthorId,proto3" json:"accepted_comment_author_id,omitempty"`
	RewardCredits           int64                  `protobuf:"varint,5,opt,name=reward_credits,json=rewardCredits,proto3" json:"reward_credits,omitempty"`
	AcceptanceCycle         int64                  `protobuf:"varint,6,opt,name=acceptance_cycle,json=acceptanceCycle,proto3" json:"acceptance_cycle,omitempty"`
	Title                   string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReverseQAAcceptanceRequest) Reset() {
	*x = ReverseQAAcceptanceRequest{}
	mi := &file_api_proto_credit_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseQAAcceptanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseQAAcceptanceRequest) ProtoMessage() {}

func (x *ReverseQAAcceptanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseQAAcceptanceRequest.ProtoReflect.Descriptor instead.
func (*ReverseQAAcceptanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{30}
}

func (x *ReverseQAAcceptanceRequest) GetQuestionAuthorId() int64 {
	if x != nil {
		return x.QuestionAuthorId
	}
	return 0
}

func (x *ReverseQAAcceptanceRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *ReverseQAAcceptanceRequest) GetAcceptedCommentId() int64 {
	if x != nil {
		return x.AcceptedCommentId
	}
	return 0
}

func (x *ReverseQAAcceptanceRequest) GetAcceptedCommentAuthorId() int64 {
	if x != nil {
		return x.AcceptedCommentAuthorId
	}
	return 0
}

func (x *ReverseQAAcceptanceRequest) GetRewardCredits() int64 {
	if x != nil {
		return x.RewardCredits
	}
	return 0
}

func (x *ReverseQAAcceptanceRequest) GetAcceptanceCycle() int64 {
	if x != nil {
		return x.AcceptanceCycle
	}
	return 0
}

func (x *ReverseQAAcceptanceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ReverseQAAcceptanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duplicate     bool                   `protobuf:"varint,1,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseQAAcceptanceResponse) Reset() {
	*x = ReverseQAAcceptanceResponse{}
	mi := &file_api_proto_credit_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseQAAcceptanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseQAAcceptanceResponse) ProtoMessage() {}

func (x *ReverseQAAcceptanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_credit_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseQAAcceptanceResponse.ProtoReflect.Descriptor instead.
func (*ReverseQAAcceptanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_credit_proto_rawDescGZIP(), []int{31}
}

func (x *ReverseQAAcceptanceResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

var File_api_proto_credit_proto protoreflect.FileDescriptor

const file_api_proto_credit_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/credit.proto\x12\rbbs.credit.v1\"W\n" +
	"\aBalance\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"\xb0\x02\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12#\n" +
	"\rbalance_after\x18\x04 \x01(\x03R\fbalanceAfter\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\a \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\b \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\t \x01(\x03R\bsourceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\xbf\x01\n" +
	"\fDailyCheckIn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"latest_day\x18\x03 \x01(\tR\tlatestDay\x12)\n" +
	"\x10consecutive_days\x18\x04 \x01(\x05R\x0fconsecutiveDays\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xe9\x02\n" +
	"\x11CreditReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\a \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\b \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\t \x01(\x03R\bsourceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"settled_at\x18\f \x01(\x03R\tsettledAt\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"C\n" +
	"\x0fBalanceResponse\x120\n" +
	"\abalance\x18\x01 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\"Z\n" +
	"\x11ListLedgerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x8e\x01\n" +
	"\x12ListLedgerResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.bbs.credit.v1.LedgerEntryR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x120\n" +
	"\abalance\x18\x03 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\"2\n" +
	"\x17GetCheckInStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x95\x01\n" +
	"\x15CheckInStatusResponse\x126\n" +
	"\bcheck_in\x18\x01 \x01(\v2\x1b.bbs.credit.v1.DailyCheckInR\acheckIn\x12\x1d\n" +
	"\n" +
	"checked_in\x18\x02 \x01(\bR\tcheckedIn\x12%\n" +
	"\x0ereward_credits\x18\x03 \x01(\x03R\rrewardCredits\")\n" +
	"\x0eCheckInRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xf4\x01\n" +
	"\x0fCheckInResponse\x126\n" +
	"\bcheck_in\x18\x01 \x01(\v2\x1b.bbs.credit.v1.DailyCheckInR\acheckIn\x120\n" +
	"\abalance\x18\x02 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x122\n" +
	"\x06ledger\x18\x03 \x01(\v2\x1a.bbs.credit.v1.LedgerEntryR\x06ledger\x12\x1c\n" +
	"\tduplicate\x18\x04 \x01(\bR\tduplicate\x12%\n" +
	"\x0ereward_credits\x18\x05 \x01(\x03R\rrewardCredits\"\x93\x01\n" +
	"\x0fTaskClaimStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x19\n" +
	"\btask_key\x18\x02 \x01(\tR\ataskKey\x12\x14\n" +
	"\x05cycle\x18\x03 \x01(\tR\x05cycle\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\bR\tcompleted\x12\x18\n" +
	"\aclaimed\x18\x05 \x01(\bR\aclaimed\"h\n" +
	"\x19GetTaskClaimStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x19\n" +
	"\btask_key\x18\x03 \x01(\tR\ataskKey\"Q\n" +
	"\x17TaskClaimStatusResponse\x126\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.bbs.credit.v1.TaskClaimStatusR\x06status\"J\n" +
	"\x14TaskClaimStatusInput\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x19\n" +
	"\btask_key\x18\x02 \x01(\tR\ataskKey\"r\n" +
	"\x1cListTaskClaimStatusesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x129\n" +
	"\x05tasks\x18\x02 \x03(\v2#.bbs.credit.v1.TaskClaimStatusInputR\x05tasks\"U\n" +
	"\x1dListTaskClaimStatusesResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.bbs.credit.v1.TaskClaimStatusR\x05items\"\xa5\x01\n" +
	"\x10ClaimTaskRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x19\n" +
	"\btask_key\x18\x03 \x01(\tR\ataskKey\x12%\n" +
	"\x0ereward_credits\x18\x04 \x01(\x03R\rrewardCredits\x12\x1d\n" +
	"\n" +
	"task_title\x18\x05 \x01(\tR\ttaskTitle\"\xcf\x01\n" +
	"\x11ClaimTaskResponse\x126\n" +
	"\x06status\x18\x01 \x01(\v2\x1e.bbs.credit.v1.TaskClaimStatusR\x06status\x120\n" +
	"\abalance\x18\x02 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x122\n" +
	"\x06ledger\x18\x03 \x01(\v2\x1a.bbs.credit.v1.LedgerEntryR\x06ledger\x12\x1c\n" +
	"\tduplicate\x18\x04 \x01(\bR\tduplicate\"\xe6\x01\n" +
	"\x13DebitCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\x05 \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\a \x01(\x03R\bsourceId\"\x9a\x01\n" +
	"\x14DebitCreditsResponse\x120\n" +
	"\abalance\x18\x01 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x122\n" +
	"\x06ledger\x18\x02 \x01(\v2\x1a.bbs.credit.v1.LedgerEntryR\x06ledger\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\"\xe5\x01\n" +
	"\x14AdjustCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\x05 \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\a \x01(\x03R\bsourceId\"\x9b\x01\n" +
	"\x15AdjustCreditsResponse\x120\n" +
	"\abalance\x18\x01 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x122\n" +
	"\x06ledger\x18\x02 \x01(\v2\x1a.bbs.credit.v1.LedgerEntryR\x06ledger\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\"\x82\x03\n" +
	"\x16TransferCreditsRequest\x12\"\n" +
	"\rpayer_user_id\x18\x01 \x01(\x03R\vpayerUserId\x12\"\n" +
	"\rpayee_user_id\x18\x02 \x01(\x03R\vpayeeUserId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12!\n" +
	"\fdebit_reason\x18\x04 \x01(\tR\vdebitReason\x12+\n" +
	"\x11debit_description\x18\x05 \x01(\tR\x10debitDescription\x12#\n" +
	"\rcredit_reason\x18\x06 \x01(\tR\fcreditReason\x12-\n" +
	"\x12credit_description\x18\a \x01(\tR\x11creditDescription\x12&\n" +
	"\x0fsource_event_id\x18\b \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\t \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\n" +
	" \x01(\x03R\bsourceId\"\x19\n" +
	"\x17TransferCreditsResponse\"\xe8\x01\n" +
	"\x15ReserveCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\x05 \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\a \x01(\x03R\bsourceId\"\xac\x01\n" +
	"\x16ReserveCreditsResponse\x120\n" +
	"\abalance\x18\x01 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x12B\n" +
	"\vreservation\x18\x02 \x01(\v2 .bbs.credit.v1.CreditReservationR\vreservation\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\"\xa6\x02\n" +
	"\x15ReleaseCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12-\n" +
	"\x12reservation_reason\x18\x03 \x01(\tR\x11reservationReason\x12%\n" +
	"\x0erelease_reason\x18\x04 \x01(\tR\rreleaseReason\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12&\n" +
	"\x0fsource_event_id\x18\x06 \x01(\tR\rsourceEventId\x12\x1f\n" +
	"\vsource_type\x18\a \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\b \x01(\x03R\bsourceId\"\xac\x01\n" +
	"\x16ReleaseCreditsResponse\x120\n" +
	"\abalance\x18\x01 \x01(\v2\x16.bbs.credit.v1.BalanceR\abalance\x12B\n" +
	"\vreservation\x18\x02 \x01(\v2 .bbs.credit.v1.CreditReservationR\vreservation\x12\x1c\n" +
	"\tduplicate\x18\x03 \x01(\bR\tduplicate\"\xba\x02\n" +
	"\x1aReverseQAAcceptanceRequest\x12,\n" +
	"\x12question_author_id\x18\x01 \x01(\x03R\x10questionAuthorId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12.\n" +
	"\x13accepted_comment_id\x18\x03 \x01(\x03R\x11acceptedCommentId\x12;\n" +
	"\x1aaccepted_comment_author_id\x18\x04 \x01(\x03R\x17acceptedCommentAuthorId\x12%\n" +
	"\x0ereward_credits\x18\x05 \x01(\x03R\rrewardCredits\x12)\n" +
	"\x10acceptance_cycle\x18\x06 \x01(\x03R\x0facceptanceCycle\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\";\n" +
	"\x1bReverseQAAcceptanceResponse\x12\x1c\n" +
	"\tduplicate\x18\x01 \x01(\bR\tduplicate2\xcd\t\n" +
	"\rCreditService\x12N\n" +
	"\n" +
	"GetBalance\x12 .bbs.credit.v1.GetBalanceRequest\x1a\x1e.bbs.credit.v1.BalanceResponse\x12Q\n" +
	"\n" +
	"ListLedger\x12 .bbs.credit.v1.ListLedgerRequest\x1a!.bbs.credit.v1.ListLedgerResponse\x12`\n" +
	"\x10GetCheckInStatus\x12&.bbs.credit.v1.GetCheckInStatusRequest\x1a$.bbs.credit.v1.CheckInStatusResponse\x12H\n" +
	"\aCheckIn\x12\x1d.bbs.credit.v1.CheckInRequest\x1a\x1e.bbs.credit.v1.CheckInResponse\x12f\n" +
	"\x12GetTaskClaimStatus\x12(.bbs.credit.v1.GetTaskClaimStatusRequest\x1a&.bbs.credit.v1.TaskClaimStatusResponse\x12r\n" +
	"\x15ListTaskClaimStatuses\x12+.bbs.credit.v1.ListTaskClaimStatusesRequest\x1a,.bbs.credit.v1.ListTaskClaimStatusesResponse\x12N\n" +
	"\tClaimTask\x12\x1f.bbs.credit.v1.ClaimTaskRequest\x1a .bbs.credit.v1.ClaimTaskResponse\x12W\n" +
	"\fDebitCredits\x12\".bbs.credit.v1.DebitCreditsRequest\x1a#.bbs.credit.v1.DebitCreditsResponse\x12Z\n" +
	"\rAdjustCredits\x12#.bbs.credit.v1.AdjustCreditsRequest\x1a$.bbs.credit.v1.AdjustCreditsResponse\x12`\n" +
	"\x0fTransferCredits\x12%.bbs.credit.v1.TransferCreditsRequest\x1a&.bbs.credit.v1.TransferCreditsResponse\x12]\n" +
	"\x0eReserveCredits\x12$.bbs.credit.v1.ReserveCreditsRequest\x1a%.bbs.credit.v1.ReserveCreditsResponse\x12]\n" +
	"\x0eReleaseCredits\x12$.bbs.credit.v1.ReleaseCreditsRequest\x1a%.bbs.credit.v1.ReleaseCreditsResponse\x12l\n" +
	"\x13ReverseQAAcceptance\x12).bbs.credit.v1.ReverseQAAcceptanceRequest\x1a*.bbs.credit.v1.ReverseQAAcceptanceResponseB,Z*credit-service/api/proto/creditpb;creditpbb\x06proto3"

var (
	file_api_proto_credit_proto_rawDescOnce sync.Once
	file_api_proto_credit_proto_rawDescData []byte
)

func file_api_proto_credit_proto_rawDescGZIP() []byte {
	file_api_proto_credit_proto_rawDescOnce.Do(func() {
		file_api_proto_credit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_credit_proto_rawDesc), len(file_api_proto_credit_proto_rawDesc)))
	})
	return file_api_proto_credit_proto_rawDescData
}

var file_api_proto_credit_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_proto_credit_proto_goTypes = []any{
	(*Balance)(nil),                       // 0: bbs.credit.v1.Balance
	(*LedgerEntry)(nil),                   // 1: bbs.credit.v1.LedgerEntry
	(*DailyCheckIn)(nil),                  // 2: bbs.credit.v1.DailyCheckIn
	(*CreditReservation)(nil),             // 3: bbs.credit.v1.CreditReservation
	(*GetBalanceRequest)(nil),             // 4: bbs.credit.v1.GetBalanceRequest
	(*BalanceResponse)(nil),               // 5: bbs.credit.v1.BalanceResponse
	(*ListLedgerRequest)(nil),             // 6: bbs.credit.v1.ListLedgerRequest
	(*ListLedgerResponse)(nil),            // 7: bbs.credit.v1.ListLedgerResponse
	(*GetCheckInStatusRequest)(nil),       // 8: bbs.credit.v1.GetCheckInStatusRequest
	(*CheckInStatusResponse)(nil),         // 9: bbs.credit.v1.CheckInStatusResponse
	(*CheckInRequest)(nil),                // 10: bbs.credit.v1.CheckInRequest
	(*CheckInResponse)(nil),               // 11: bbs.credit.v1.CheckInResponse
	(*TaskClaimStatus)(nil),               // 12: bbs.credit.v1.TaskClaimStatus
	(*GetTaskClaimStatusRequest)(nil),     // 13: bbs.credit.v1.GetTaskClaimStatusRequest
	(*TaskClaimStatusResponse)(nil),       // 14: bbs.credit.v1.TaskClaimStatusResponse
	(*TaskClaimStatusInput)(nil),          // 15: bbs.credit.v1.TaskClaimStatusInput
	(*ListTaskClaimStatusesRequest)(nil),  // 16: bbs.credit.v1.ListTaskClaimStatusesRequest
	(*ListTaskClaimStatusesResponse)(nil), // 17: bbs.credit.v1.ListTaskClaimStatusesResponse
	(*ClaimTaskRequest)(nil),              // 18: bbs.credit.v1.ClaimTaskRequest
	(*ClaimTaskResponse)(nil),             // 19: bbs.credit.v1.ClaimTaskResponse
	(*DebitCreditsRequest)(nil),           // 20: bbs.credit.v1.DebitCreditsRequest
	(*DebitCreditsResponse)(nil),          // 21: bbs.credit.v1.DebitCreditsResponse
	(*AdjustCreditsRequest)(nil),          // 22: bbs.credit.v1.AdjustCreditsRequest
	(*AdjustCreditsResponse)(nil),         // 23: bbs.credit.v1.AdjustCreditsResponse
	(*TransferCreditsRequest)(nil),        // 24: bbs.credit.v1.TransferCreditsRequest
	(*TransferCreditsResponse)(nil),       // 25: bbs.credit.v1.TransferCreditsResponse
	(*ReserveCreditsRequest)(nil),         // 26: bbs.credit.v1.ReserveCreditsRequest
	(*ReserveCreditsResponse)(nil),        // 27: bbs.credit.v1.ReserveCreditsResponse
	(*ReleaseCreditsRequest)(nil),         // 28: bbs.credit.v1.ReleaseCreditsRequest
	(*ReleaseCreditsResponse)(nil),        // 29: bbs.credit.v1.ReleaseCreditsResponse
	(*ReverseQAAcceptanceRequest)(nil),    // 30: bbs.credit.v1.ReverseQAAcceptanceRequest
	(*ReverseQAAcceptanceResponse)(nil),   // 31: bbs.credit.v1.ReverseQAAcceptanceResponse
}
var file_api_proto_credit_proto_depIdxs = []int32{
	0,  // 0: bbs.credit.v1.BalanceResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 1: bbs.credit.v1.ListLedgerResponse.items:type_name -> bbs.credit.v1.LedgerEntry
	0,  // 2: bbs.credit.v1.ListLedgerResponse.balance:type_name -> bbs.credit.v1.Balance
	2,  // 3: bbs.credit.v1.CheckInStatusResponse.check_in:type_name -> bbs.credit.v1.DailyCheckIn
	2,  // 4: bbs.credit.v1.CheckInResponse.check_in:type_name -> bbs.credit.v1.DailyCheckIn
	0,  // 5: bbs.credit.v1.CheckInResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 6: bbs.credit.v1.CheckInResponse.ledger:type_name -> bbs.credit.v1.LedgerEntry
	12, // 7: bbs.credit.v1.TaskClaimStatusResponse.status:type_name -> bbs.credit.v1.TaskClaimStatus
	15, // 8: bbs.credit.v1.ListTaskClaimStatusesRequest.tasks:type_name -> bbs.credit.v1.TaskClaimStatusInput
	12, // 9: bbs.credit.v1.ListTaskClaimStatusesResponse.items:type_name -> bbs.credit.v1.TaskClaimStatus
	12, // 10: bbs.credit.v1.ClaimTaskResponse.status:type_name -> bbs.credit.v1.TaskClaimStatus
	0,  // 11: bbs.credit.v1.ClaimTaskResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 12: bbs.credit.v1.ClaimTaskResponse.ledger:type_name -> bbs.credit.v1.LedgerEntry
	0,  // 13: bbs.credit.v1.DebitCreditsResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 14: bbs.credit.v1.DebitCreditsResponse.ledger:type_name -> bbs.credit.v1.LedgerEntry
	0,  // 15: bbs.credit.v1.AdjustCreditsResponse.balance:type_name -> bbs.credit.v1.Balance
	1,  // 16: bbs.credit.v1.AdjustCreditsResponse.ledger:type_name -> bbs.credit.v1.LedgerEntry
	0,  // 17: bbs.credit.v1.ReserveCreditsResponse.balance:type_name -> bbs.credit.v1.Balance
	3,  // 18: bbs.credit.v1.ReserveCreditsResponse.reservation:type_name -> bbs.credit.v1.CreditReservation
	0,  // 19: bbs.credit.v1.ReleaseCreditsResponse.balance:type_name -> bbs.credit.v1.Balance
	3,  // 20: bbs.credit.v1.ReleaseCreditsResponse.reservation:type_name -> bbs.credit.v1.CreditReservation
	4,  // 21: bbs.credit.v1.CreditService.GetBalance:input_type -> bbs.credit.v1.GetBalanceRequest
	6,  // 22: bbs.credit.v1.CreditService.ListLedger:input_type -> bbs.credit.v1.ListLedgerRequest
	8,  // 23: bbs.credit.v1.CreditService.GetCheckInStatus:input_type -> bbs.credit.v1.GetCheckInStatusRequest
	10, // 24: bbs.credit.v1.CreditService.CheckIn:input_type -> bbs.credit.v1.CheckInRequest
	13, // 25: bbs.credit.v1.CreditService.GetTaskClaimStatus:input_type -> bbs.credit.v1.GetTaskClaimStatusRequest
	16, // 26: bbs.credit.v1.CreditService.ListTaskClaimStatuses:input_type -> bbs.credit.v1.ListTaskClaimStatusesRequest
	18, // 27: bbs.credit.v1.CreditService.ClaimTask:input_type -> bbs.credit.v1.ClaimTaskRequest
	20, // 28: bbs.credit.v1.CreditService.DebitCredits:input_type -> bbs.credit.v1.DebitCreditsRequest
	22, // 29: bbs.credit.v1.CreditService.AdjustCredits:input_type -> bbs.credit.v1.AdjustCreditsRequest
	24, // 30: bbs.credit.v1.CreditService.TransferCredits:input_type -> bbs.credit.v1.TransferCreditsRequest
	26, // 31: bbs.credit.v1.CreditService.ReserveCredits:input_type -> bbs.credit.v1.ReserveCreditsRequest
	28, // 32: bbs.credit.v1.CreditService.ReleaseCredits:input_type -> bbs.credit.v1.ReleaseCreditsRequest
	30, // 33: bbs.credit.v1.CreditService.ReverseQAAcceptance:input_type -> bbs.credit.v1.ReverseQAAcceptanceRequest
	5,  // 34: bbs.credit.v1.CreditService.GetBalance:output_type -> bbs.credit.v1.BalanceResponse
	7,  // 35: bbs.credit.v1.CreditService.ListLedger:output_type -> bbs.credit.v1.ListLedgerResponse
	9,  // 36: bbs.credit.v1.CreditService.GetCheckInStatus:output_type -> bbs.credit.v1.CheckInStatusResponse
	11, // 37: bbs.credit.v1.CreditService.CheckIn:output_type -> bbs.credit.v1.CheckInResponse
	14, // 38: bbs.credit.v1.CreditService.GetTaskClaimStatus:output_type -> bbs.credit.v1.TaskClaimStatusResponse
	17, // 39: bbs.credit.v1.CreditService.ListTaskClaimStatuses:output_type -> bbs.credit.v1.ListTaskClaimStatusesResponse
	19, // 40: bbs.credit.v1.CreditService.ClaimTask:output_type -> bbs.credit.v1.ClaimTaskResponse
	21, // 41: bbs.credit.v1.CreditService.DebitCredits:output_type -> bbs.credit.v1.DebitCreditsResponse
	23, // 42: bbs.credit.v1.CreditService.AdjustCredits:output_type -> bbs.credit.v1.AdjustCreditsResponse
	25, // 43: bbs.credit.v1.CreditService.TransferCredits:output_type -> bbs.credit.v1.TransferCreditsResponse
	27, // 44: bbs.credit.v1.CreditService.ReserveCredits:output_type -> bbs.credit.v1.ReserveCreditsResponse
	29, // 45: bbs.credit.v1.CreditService.ReleaseCredits:output_type -> bbs.credit.v1.ReleaseCreditsResponse
	31, // 46: bbs.credit.v1.CreditService.ReverseQAAcceptance:output_type -> bbs.credit.v1.ReverseQAAcceptanceResponse
	34, // [34:47] is the sub-list for method output_type
	21, // [21:34] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_proto_credit_proto_init() }
func file_api_proto_credit_proto_init() {
	if File_api_proto_credit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_credit_proto_rawDesc), len(file_api_proto_credit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_credit_proto_goTypes,
		DependencyIndexes: file_api_proto_credit_proto_depIdxs,
		MessageInfos:      file_api_proto_credit_proto_msgTypes,
	}.Build()
	File_api_proto_credit_proto = out.File
	file_api_proto_credit_proto_goTypes = nil
	file_api_proto_credit_proto_depIdxs = nil
}
