service:
  name: bbs-file-service
  grpcPort: 9111

app:
  name: bbs-file-service

nacos:
  addr: "127.0.0.1"
  port: 8848
  namespaceId: ""
  dataId: "bbs-file-service.yaml"
  groupId: "DEFAULT_GROUP"

postgres:
  dsn: postgres://bbs_file_app:local_file_pass@127.0.0.1:5432/bbs?sslmode=disable&search_path=bbs_file

storage:
  provider: minio
  endpoint: http://127.0.0.1:9000
  bucket: bbs-local
  accessKey: minioadmin
  secretKey: minioadmin

upstreams:
  credit: bbs-credit-service
  content: bbs-content-service
  mall: bbs-mall-service

grpc:
  server:
    port: 9111
    etcdAddr:
      - "127.0.0.1:2379"
    serviceName: "bbs-file-service"
  client:
    etcdAddr:
      - "127.0.0.1:2379"
