package topic

import "errors"

var (
	ErrSlugRequired                           = errors.New("TOPIC_SLUG_REQUIRED")
	ErrTitleRequired                          = errors.New("TOPIC_TITLE_REQUIRED")
	ErrBodyRequired                           = errors.New("TOPIC_BODY_REQUIRED")
	ErrAuthorRequired                         = errors.New("TOPIC_AUTHOR_REQUIRED")
	ErrBountyInvalid                          = errors.New("TOPIC_BOUNTY_INVALID")
	ErrBountyCreditInsufficient               = errors.New("TOPIC_BOUNTY_CREDIT_INSUFFICIENT")
	ErrBountyCreditReleaseFailed              = errors.New("TOPIC_BOUNTY_CREDIT_RELEASE_FAILED")
	ErrQAAcceptanceOutboxUnavailable          = errors.New("TOPIC_QA_ACCEPTANCE_OUTBOX_UNAVAILABLE")
	ErrQAAcceptanceOutboxNotFound             = errors.New("TOPIC_QA_ACCEPTANCE_OUTBOX_NOT_FOUND")
	ErrInvalidComment                         = errors.New("TOPIC_ACCEPTED_COMMENT_INVALID")
	ErrNotQuestion                            = errors.New("TOPIC_NOT_QUESTION")
	ErrMembershipEntitlementRequired          = errors.New("TOPIC_MEMBERSHIP_ENTITLEMENT_REQUIRED")
	ErrCommentNotFound                        = errors.New("TOPIC_COMMENT_NOT_FOUND")
	ErrCommentNotInTopic                      = errors.New("TOPIC_COMMENT_NOT_IN_TOPIC")
	ErrAlreadyAccepted                        = errors.New("TOPIC_COMMENT_ALREADY_ACCEPTED")
	ErrNotAccepted                            = errors.New("TOPIC_COMMENT_NOT_ACCEPTED")
	ErrCannotAcceptOwnComment                 = errors.New("TOPIC_CANNOT_ACCEPT_OWN_COMMENT")
	ErrQAAcceptanceSettlementPending          = errors.New("TOPIC_QA_ACCEPTANCE_SETTLEMENT_PENDING")
	ErrQAAcceptanceReversalInsufficientCredit = errors.New("TOPIC_QA_ACCEPTANCE_REVERSAL_INSUFFICIENT_CREDIT")
	ErrTopicOwnerMismatch                     = errors.New("TOPIC_OWNER_MISMATCH")
	ErrChannelNotFound                        = errors.New("TOPIC_CHANNEL_NOT_FOUND")
	ErrChannelArchived                        = errors.New("TOPIC_CHANNEL_ARCHIVED")
	ErrNotFound                               = errors.New("TOPIC_NOT_FOUND")
	ErrSlugExists                             = errors.New("TOPIC_SLUG_EXISTS")
	ErrAlreadyPublished                       = errors.New("TOPIC_ALREADY_PUBLISHED")
	ErrNotPublished                           = errors.New("TOPIC_NOT_PUBLISHED")
	ErrArchived                               = errors.New("TOPIC_ARCHIVED")
	ErrPollNotFound                           = errors.New("TOPIC_POLL_NOT_FOUND")
	ErrPollChoicesInvalid                     = errors.New("TOPIC_POLL_CHOICES_INVALID")
	ErrPollChoiceInvalid                      = errors.New("TOPIC_POLL_CHOICE_INVALID")
	ErrPollChoiceDuplicate                    = errors.New("TOPIC_POLL_CHOICE_DUPLICATE")
	ErrPollExpiryInvalid                      = errors.New("TOPIC_POLL_EXPIRY_INVALID")
	ErrPollSelectionInvalid                   = errors.New("TOPIC_POLL_SELECTION_INVALID")
	ErrPollExpired                            = errors.New("TOPIC_POLL_EXPIRED")
	ErrPollAlreadyVoted                       = errors.New("TOPIC_POLL_ALREADY_VOTED")
	ErrPollLocked                             = errors.New("TOPIC_POLL_LOCKED")
)
