// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.1
// source: api/proto/content.proto

package contentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentService_CreateTopic_FullMethodName        = "/bbs.content.v1.ContentService/CreateTopic"
	ContentService_UpdateTopic_FullMethodName        = "/bbs.content.v1.ContentService/UpdateTopic"
	ContentService_PublishTopic_FullMethodName       = "/bbs.content.v1.ContentService/PublishTopic"
	ContentService_HideTopic_FullMethodName          = "/bbs.content.v1.ContentService/HideTopic"
	ContentService_ArchiveTopic_FullMethodName       = "/bbs.content.v1.ContentService/ArchiveTopic"
	ContentService_AcceptTopicComment_FullMethodName = "/bbs.content.v1.ContentService/AcceptTopicComment"
	ContentService_GetTopic_FullMethodName           = "/bbs.content.v1.ContentService/GetTopic"
	ContentService_ListTopics_FullMethodName         = "/bbs.content.v1.ContentService/ListTopics"
	ContentService_CreateArticle_FullMethodName      = "/bbs.content.v1.ContentService/CreateArticle"
	ContentService_UpdateArticle_FullMethodName      = "/bbs.content.v1.ContentService/UpdateArticle"
	ContentService_PublishArticle_FullMethodName     = "/bbs.content.v1.ContentService/PublishArticle"
	ContentService_HideArticle_FullMethodName        = "/bbs.content.v1.ContentService/HideArticle"
	ContentService_ArchiveArticle_FullMethodName     = "/bbs.content.v1.ContentService/ArchiveArticle"
	ContentService_GetArticle_FullMethodName         = "/bbs.content.v1.ContentService/GetArticle"
	ContentService_ListArticles_FullMethodName       = "/bbs.content.v1.ContentService/ListArticles"
	ContentService_FeedArticlesByTime_FullMethodName = "/bbs.content.v1.ContentService/FeedArticlesByTime"
	ContentService_ListCategories_FullMethodName     = "/bbs.content.v1.ContentService/ListCategories"
	ContentService_GetCategory_FullMethodName        = "/bbs.content.v1.ContentService/GetCategory"
	ContentService_CreateCategory_FullMethodName     = "/bbs.content.v1.ContentService/CreateCategory"
	ContentService_UpdateCategory_FullMethodName     = "/bbs.content.v1.ContentService/UpdateCategory"
	ContentService_DeleteCategory_FullMethodName     = "/bbs.content.v1.ContentService/DeleteCategory"
	ContentService_ListTags_FullMethodName           = "/bbs.content.v1.ContentService/ListTags"
	ContentService_AutocompleteTags_FullMethodName   = "/bbs.content.v1.ContentService/AutocompleteTags"
)

// ContentServiceClient is the client API for ContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentServiceClient interface {
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	UpdateTopic(ctx context.Context, in *UpdateTopicRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	PublishTopic(ctx context.Context, in *TopicIDRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	HideTopic(ctx context.Context, in *TopicIDRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	ArchiveTopic(ctx context.Context, in *TopicIDRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	AcceptTopicComment(ctx context.Context, in *AcceptTopicCommentRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*TopicResponse, error)
	ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*TopicListResponse, error)
	CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	PublishArticle(ctx context.Context, in *ArticleIDRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	HideArticle(ctx context.Context, in *ArticleIDRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	ArchiveArticle(ctx context.Context, in *ArticleIDRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ArticleListResponse, error)
	FeedArticlesByTime(ctx context.Context, in *FeedArticlesByTimeRequest, opts ...grpc.CallOption) (*ArticleListResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*CategoryListResponse, error)
	GetCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	CreateCategory(ctx context.Context, in *UpsertCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpsertCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	DeleteCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*CategoryResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*TagListResponse, error)
	AutocompleteTags(ctx context.Context, in *AutocompleteTagsRequest, opts ...grpc.CallOption) (*TagListResponse, error)
}

type contentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContentServiceClient(cc grpc.ClientConnInterface) ContentServiceClient {
	return &contentServiceClient{cc}
}

func (c *contentServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, ContentService_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateTopic(ctx context.Context, in *UpdateTopicRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, ContentService_UpdateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) PublishTopic(ctx context.Context, in *TopicIDRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, ContentService_PublishTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) HideTopic(ctx context.Context, in *TopicIDRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, ContentService_HideTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) ArchiveTopic(ctx context.Context, in *TopicIDRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, ContentService_ArchiveTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) AcceptTopicComment(ctx context.Context, in *AcceptTopicCommentRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, ContentService_AcceptTopicComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*TopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicResponse)
	err := c.cc.Invoke(ctx, ContentService_GetTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*TopicListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicListResponse)
	err := c.cc.Invoke(ctx, ContentService_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ContentService_CreateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ContentService_UpdateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) PublishArticle(ctx context.Context, in *ArticleIDRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ContentService_PublishArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) HideArticle(ctx context.Context, in *ArticleIDRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ContentService_HideArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) ArchiveArticle(ctx context.Context, in *ArticleIDRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ContentService_ArchiveArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ContentService_GetArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ArticleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleListResponse)
	err := c.cc.Invoke(ctx, ContentService_ListArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) FeedArticlesByTime(ctx context.Context, in *FeedArticlesByTimeRequest, opts ...grpc.CallOption) (*ArticleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleListResponse)
	err := c.cc.Invoke(ctx, ContentService_FeedArticlesByTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*CategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryListResponse)
	err := c.cc.Invoke(ctx, ContentService_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, ContentService_GetCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) CreateCategory(ctx context.Context, in *UpsertCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, ContentService_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) UpdateCategory(ctx context.Context, in *UpsertCategoryRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, ContentService_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) DeleteCategory(ctx context.Context, in *CategoryIDRequest, opts ...grpc.CallOption) (*CategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryResponse)
	err := c.cc.Invoke(ctx, ContentService_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*TagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagListResponse)
	err := c.cc.Invoke(ctx, ContentService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) AutocompleteTags(ctx context.Context, in *AutocompleteTagsRequest, opts ...grpc.CallOption) (*TagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagListResponse)
	err := c.cc.Invoke(ctx, ContentService_AutocompleteTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServiceServer is the server API for ContentService service.
// All implementations must embed UnimplementedContentServiceServer
// for forward compatibility.
type ContentServiceServer interface {
	CreateTopic(context.Context, *CreateTopicRequest) (*TopicResponse, error)
	UpdateTopic(context.Context, *UpdateTopicRequest) (*TopicResponse, error)
	PublishTopic(context.Context, *TopicIDRequest) (*TopicResponse, error)
	HideTopic(context.Context, *TopicIDRequest) (*TopicResponse, error)
	ArchiveTopic(context.Context, *TopicIDRequest) (*TopicResponse, error)
	AcceptTopicComment(context.Context, *AcceptTopicCommentRequest) (*TopicResponse, error)
	GetTopic(context.Context, *GetTopicRequest) (*TopicResponse, error)
	ListTopics(context.Context, *ListTopicsRequest) (*TopicListResponse, error)
	CreateArticle(context.Context, *CreateArticleRequest) (*ArticleResponse, error)
	UpdateArticle(context.Context, *UpdateArticleRequest) (*ArticleResponse, error)
	PublishArticle(context.Context, *ArticleIDRequest) (*ArticleResponse, error)
	HideArticle(context.Context, *ArticleIDRequest) (*ArticleResponse, error)
	ArchiveArticle(context.Context, *ArticleIDRequest) (*ArticleResponse, error)
	GetArticle(context.Context, *GetArticleRequest) (*ArticleResponse, error)
	ListArticles(context.Context, *ListArticlesRequest) (*ArticleListResponse, error)
	FeedArticlesByTime(context.Context, *FeedArticlesByTimeRequest) (*ArticleListResponse, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*CategoryListResponse, error)
	GetCategory(context.Context, *CategoryIDRequest) (*CategoryResponse, error)
	CreateCategory(context.Context, *UpsertCategoryRequest) (*CategoryResponse, error)
	UpdateCategory(context.Context, *UpsertCategoryRequest) (*CategoryResponse, error)
	DeleteCategory(context.Context, *CategoryIDRequest) (*CategoryResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*TagListResponse, error)
	AutocompleteTags(context.Context, *AutocompleteTagsRequest) (*TagListResponse, error)
	mustEmbedUnimplementedContentServiceServer()
}

// UnimplementedContentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentServiceServer struct{}

func (UnimplementedContentServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*TopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedContentServiceServer) UpdateTopic(context.Context, *UpdateTopicRequest) (*TopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTopic not implemented")
}
func (UnimplementedContentServiceServer) PublishTopic(context.Context, *TopicIDRequest) (*TopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTopic not implemented")
}
func (UnimplementedContentServiceServer) HideTopic(context.Context, *TopicIDRequest) (*TopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HideTopic not implemented")
}
func (UnimplementedContentServiceServer) ArchiveTopic(context.Context, *TopicIDRequest) (*TopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveTopic not implemented")
}
func (UnimplementedContentServiceServer) AcceptTopicComment(context.Context, *AcceptTopicCommentRequest) (*TopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptTopicComment not implemented")
}
func (UnimplementedContentServiceServer) GetTopic(context.Context, *GetTopicRequest) (*TopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopic not implemented")
}
func (UnimplementedContentServiceServer) ListTopics(context.Context, *ListTopicsRequest) (*TopicListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedContentServiceServer) CreateArticle(context.Context, *CreateArticleRequest) (*ArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArticle not implemented")
}
func (UnimplementedContentServiceServer) UpdateArticle(context.Context, *UpdateArticleRequest) (*ArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedContentServiceServer) PublishArticle(context.Context, *ArticleIDRequest) (*ArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishArticle not implemented")
}
func (UnimplementedContentServiceServer) HideArticle(context.Context, *ArticleIDRequest) (*ArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HideArticle not implemented")
}
func (UnimplementedContentServiceServer) ArchiveArticle(context.Context, *ArticleIDRequest) (*ArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveArticle not implemented")
}
func (UnimplementedContentServiceServer) GetArticle(context.Context, *GetArticleRequest) (*ArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedContentServiceServer) ListArticles(context.Context, *ListArticlesRequest) (*ArticleListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArticles not implemented")
}
func (UnimplementedContentServiceServer) FeedArticlesByTime(context.Context, *FeedArticlesByTimeRequest) (*ArticleListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FeedArticlesByTime not implemented")
}
func (UnimplementedContentServiceServer) ListCategories(context.Context, *ListCategoriesRequest) (*CategoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedContentServiceServer) GetCategory(context.Context, *CategoryIDRequest) (*CategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedContentServiceServer) CreateCategory(context.Context, *UpsertCategoryRequest) (*CategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedContentServiceServer) UpdateCategory(context.Context, *UpsertCategoryRequest) (*CategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedContentServiceServer) DeleteCategory(context.Context, *CategoryIDRequest) (*CategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedContentServiceServer) ListTags(context.Context, *ListTagsRequest) (*TagListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedContentServiceServer) AutocompleteTags(context.Context, *AutocompleteTagsRequest) (*TagListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutocompleteTags not implemented")
}
func (UnimplementedContentServiceServer) mustEmbedUnimplementedContentServiceServer() {}
func (UnimplementedContentServiceServer) testEmbeddedByValue()                        {}

// UnsafeContentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentServiceServer will
// result in compilation errors.
type UnsafeContentServiceServer interface {
	mustEmbedUnimplementedContentServiceServer()
}

func RegisterContentServiceServer(s grpc.ServiceRegistrar, srv ContentServiceServer) {
	// If the following call panics, it indicates UnimplementedContentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentService_ServiceDesc, srv)
}

func _ContentService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_UpdateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateTopic(ctx, req.(*UpdateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_PublishTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).PublishTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_PublishTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).PublishTopic(ctx, req.(*TopicIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_HideTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).HideTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_HideTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).HideTopic(ctx, req.(*TopicIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_ArchiveTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).ArchiveTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_ArchiveTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).ArchiveTopic(ctx, req.(*TopicIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_AcceptTopicComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptTopicCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).AcceptTopicComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_AcceptTopicComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).AcceptTopicComment(ctx, req.(*AcceptTopicCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_GetTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetTopic(ctx, req.(*GetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).ListTopics(ctx, req.(*ListTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_CreateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_CreateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateArticle(ctx, req.(*CreateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_UpdateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateArticle(ctx, req.(*UpdateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_PublishArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).PublishArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_PublishArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).PublishArticle(ctx, req.(*ArticleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_HideArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).HideArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_HideArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).HideArticle(ctx, req.(*ArticleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_ArchiveArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).ArchiveArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_ArchiveArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).ArchiveArticle(ctx, req.(*ArticleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_GetArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetArticle(ctx, req.(*GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_ListArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).ListArticles(ctx, req.(*ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_FeedArticlesByTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedArticlesByTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).FeedArticlesByTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_FeedArticlesByTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).FeedArticlesByTime(ctx, req.(*FeedArticlesByTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetCategory(ctx, req.(*CategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).CreateCategory(ctx, req.(*UpsertCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).UpdateCategory(ctx, req.(*UpsertCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).DeleteCategory(ctx, req.(*CategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_AutocompleteTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutocompleteTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).AutocompleteTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentService_AutocompleteTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).AutocompleteTags(ctx, req.(*AutocompleteTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentService_ServiceDesc is the grpc.ServiceDesc for ContentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bbs.content.v1.ContentService",
	HandlerType: (*ContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _ContentService_CreateTopic_Handler,
		},
		{
			MethodName: "UpdateTopic",
			Handler:    _ContentService_UpdateTopic_Handler,
		},
		{
			MethodName: "PublishTopic",
			Handler:    _ContentService_PublishTopic_Handler,
		},
		{
			MethodName: "HideTopic",
			Handler:    _ContentService_HideTopic_Handler,
		},
		{
			MethodName: "ArchiveTopic",
			Handler:    _ContentService_ArchiveTopic_Handler,
		},
		{
			MethodName: "AcceptTopicComment",
			Handler:    _ContentService_AcceptTopicComment_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _ContentService_GetTopic_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _ContentService_ListTopics_Handler,
		},
		{
			MethodName: "CreateArticle",
			Handler:    _ContentService_CreateArticle_Handler,
		},
		{
			MethodName: "UpdateArticle",
			Handler:    _ContentService_UpdateArticle_Handler,
		},
		{
			MethodName: "PublishArticle",
			Handler:    _ContentService_PublishArticle_Handler,
		},
		{
			MethodName: "HideArticle",
			Handler:    _ContentService_HideArticle_Handler,
		},
		{
			MethodName: "ArchiveArticle",
			Handler:    _ContentService_ArchiveArticle_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _ContentService_GetArticle_Handler,
		},
		{
			MethodName: "ListArticles",
			Handler:    _ContentService_ListArticles_Handler,
		},
		{
			MethodName: "FeedArticlesByTime",
			Handler:    _ContentService_FeedArticlesByTime_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _ContentService_ListCategories_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _ContentService_GetCategory_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _ContentService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _ContentService_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _ContentService_DeleteCategory_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _ContentService_ListTags_Handler,
		},
		{
			MethodName: "AutocompleteTags",
			Handler:    _ContentService_AutocompleteTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/content.proto",
}
